# -*- coding: utf-8 -*-
"""
离散数学内置试题库数据模块。

按 Rosen《离散数学及其应用》教材的 13 章 + 跨章节综合题组织，
全部使用中文描述，覆盖选择/填空/计算/证明/判断/简答六种题型，
覆盖各章节核心知识点，便于组卷、练习与教学。

提供 import_quiz_data() 函数，用于清空并重建试题库。
"""

from datetime import datetime


# 章节标题对照表
CHAPTER_TITLES = {
    "第1章": "逻辑与证明",
    "第2章": "集合与函数",
    "第3章": "算法",
    "第4章": "数论与密码学",
    "第5章": "归纳与递归",
    "第6章": "计数",
    "第7章": "离散概率",
    "第8章": "高级计数",
    "第9章": "关系",
    "第10章": "图论",
    "第11章": "树",
    "第12章": "布尔代数",
    "第13章": "计算模型",
}


# 题型中文对照
QUESTION_TYPE_NAMES = {
    "choice": "选择题",
    "fill": "填空题",
    "calc": "计算题",
    "proof": "证明题",
    "true_false": "判断题",
    "short_answer": "简答题",
}


QUIZ_DATA = [
    # ===================== 第1章 逻辑与证明 (25题) =====================
    {
        "chapter": "第1章", "section": "1.3", "question_type": "choice", "difficulty": "easy",
        "question_text": "命题 p→q 的逆否命题是？",
        "options": "A. q→p\nB. ¬q→¬p\nC. ¬p→¬q\nD. p↔q",
        "answer": "B",
        "answer_cn": "B. ¬q→¬p。逆否命题是将原命题的前后件同时取否并交换位置，p→q 的逆否命题为 ¬q→¬p，二者逻辑等价。",
        "tags": "命题,逆否命题,蕴含",
    },
    {
        "chapter": "第1章", "section": "1.3", "question_type": "choice", "difficulty": "easy",
        "question_text": "下列等价式正确的是？",
        "options": "A. ¬(p∧q) ≡ ¬p∧¬q\nB. ¬(p∨q) ≡ ¬p∨¬q\nC. ¬(p∧q) ≡ ¬p∨¬q\nD. p→q ≡ ¬q→¬p 之外不存在等价",
        "answer": "C",
        "answer_cn": "C. ¬(p∧q) ≡ ¬p∨¬q。这是德摩根律，合取的否定等于否定的析取。A、B 违反德摩根律。",
        "tags": "德摩根律,等价式",
    },
    {
        "chapter": "第1章", "section": "1.1", "question_type": "choice", "difficulty": "easy",
        "question_text": "命题 p→q 为假，当且仅当？",
        "options": "A. p真q真\nB. p真q假\nC. p假q真\nD. p假q假",
        "answer": "B",
        "answer_cn": "B. p真q假。蕴含 p→q 仅在前件 p 真而后件 q 假时为假，其余三种情况均为真。",
        "tags": "蕴含,真值表",
    },
    {
        "chapter": "第1章", "section": "1.1", "question_type": "choice", "difficulty": "easy",
        "question_text": "双条件命题 p↔q 为真，当且仅当？",
        "options": "A. p真q真\nB. p假q假\nC. p与q真值相同\nD. p与q真值不同",
        "answer": "C",
        "answer_cn": "C. p与q真值相同。p↔q 当且仅当 p 与 q 同真或同假时为真，即二者真值相同。",
        "tags": "双条件,等价",
    },
    {
        "chapter": "第1章", "section": "1.1", "question_type": "choice", "difficulty": "medium",
        "question_text": "异或 p⊕q 为真，当且仅当？",
        "options": "A. p与q都为真\nB. p与q都为假\nC. p与q恰有一个为真\nD. p与q真值相同",
        "answer": "C",
        "answer_cn": "C. p与q恰有一个为真。异或（不可兼或）当且仅当 p、q 恰有一个为真时为真，可写为 (p∨q)∧¬(p∧q)。",
        "tags": "异或,不可兼或",
    },
    {
        "chapter": "第1章", "section": "1.3", "question_type": "choice", "difficulty": "medium",
        "question_text": "命题公式 ¬(p→q) 等价于？",
        "options": "A. ¬p→¬q\nB. p∧¬q\nC. ¬p∧q\nD. p∨¬q",
        "answer": "B",
        "answer_cn": "B. p∧¬q。由 p→q ≡ ¬p∨q，故 ¬(p→q) ≡ ¬(¬p∨q) ≡ p∧¬q（德摩根律）。这是常见易错点：蕴含的否定不是 ¬p→¬q。",
        "tags": "蕴含的否定,德摩根律",
    },
    {
        "chapter": "第1章", "section": "1.3", "question_type": "choice", "difficulty": "hard",
        "question_text": "命题公式 p∨(q∧r) 的主析取范式包含多少个最小项？",
        "options": "A. 4\nB. 5\nC. 6\nD. 7",
        "answer": "D",
        "answer_cn": "D. 7。p∨(q∧r) 在 8 种赋值中仅当 p=0,q=0,r=0 时为假（m₀），其余 7 种赋值均为真，故主析取范式含 7 个最小项 m₁,m₂,…,m₇。",
        "tags": "主析取范式,最小项",
    },
    {
        "chapter": "第1章", "section": "1.5", "question_type": "choice", "difficulty": "medium",
        "question_text": "¬∃x P(x) 等价于？",
        "options": "A. ∃x ¬P(x)\nB. ∀x ¬P(x)\nC. ∀x P(x)\nD. ∃x P(x)",
        "answer": "B",
        "answer_cn": "B. ∀x ¬P(x)。存在量词的否定等于全称量词否定谓词：¬∃x P(x) ≡ ∀x ¬P(x)，这是量词德摩根律。",
        "tags": "量词否定,谓词逻辑",
    },
    {
        "chapter": "第1章", "section": "1.5", "question_type": "choice", "difficulty": "medium",
        "question_text": "∀x(P(x)→Q(x)) 的含义是？",
        "options": "A. 存在 x 使 P(x) 成立则 Q(x) 成立\nB. 对所有 x，P(x) 与 Q(x) 都成立\nC. 对所有 x，若 P(x) 成立则 Q(x) 成立\nD. 对所有 x，P(x) 与 Q(x) 等价",
        "answer": "C",
        "answer_cn": "C. 对所有 x，若 P(x) 成立则 Q(x) 成立。全称量词作用域内的蕴含表示对每个个体 x，P(x) 都蕴含 Q(x)。",
        "tags": "全称量词,谓词蕴含",
    },
    {
        "chapter": "第1章", "section": "1.6", "question_type": "choice", "difficulty": "easy",
        "question_text": "假言推理（modus ponens）的形式是？",
        "options": "A. p→q，¬q ⊢ ¬p\nB. p→q，p ⊢ q\nC. p→q，q ⊢ p\nD. p，q ⊢ p∧q",
        "answer": "B",
        "answer_cn": "B. p→q，p ⊢ q。由 p→q 与 p 同时成立可推出 q，这是假言推理（肯定前件式）。选项 A 是拒取式。",
        "tags": "推理规则,假言推理",
    },
    {
        "chapter": "第1章", "section": "1.1", "question_type": "fill", "difficulty": "easy",
        "question_text": "能够判断真假的陈述句称为____。",
        "options": "",
        "answer": "命题",
        "answer_cn": "命题。命题是能够判断真假的陈述句，其真值唯一：真或假。",
        "tags": "命题,定义",
    },
    {
        "chapter": "第1章", "section": "1.1", "question_type": "fill", "difficulty": "easy",
        "question_text": "在蕴含 p→q 中，当 p 为假时，p→q 的真值为____。",
        "options": "",
        "answer": "真（T）",
        "answer_cn": "真（T）。前件为假时蕴含空真（vacuously true），不论 q 真假，p→q 均为真。",
        "tags": "蕴含,空真",
    },
    {
        "chapter": "第1章", "section": "1.3", "question_type": "fill", "difficulty": "easy",
        "question_text": "¬(¬p) 等价于____。",
        "options": "",
        "answer": "p",
        "answer_cn": "p。双重否定律：¬(¬p) ≡ p。",
        "tags": "双重否定,等价式",
    },
    {
        "chapter": "第1章", "section": "1.5", "question_type": "fill", "difficulty": "medium",
        "question_text": "¬∀x P(x) 等价于____。",
        "options": "",
        "answer": "∃x ¬P(x)",
        "answer_cn": "∃x ¬P(x)。全称量词的否定等于存在量词否定谓词：¬∀x P(x) ≡ ∃x ¬P(x)。",
        "tags": "量词否定,谓词逻辑",
    },
    {
        "chapter": "第1章", "section": "1.1", "question_type": "fill", "difficulty": "easy",
        "question_text": "含有 n 个命题变元的真值表共有____行。",
        "options": "",
        "answer": "2ⁿ",
        "answer_cn": "2ⁿ。n 个变元每个有真假两种取值，故共 2ⁿ 种赋值组合，对应真值表 2ⁿ 行。",
        "tags": "真值表,赋值",
    },
    {
        "chapter": "第1章", "section": "1.3", "question_type": "calc", "difficulty": "medium",
        "question_text": "用真值表判定命题公式 (p→q)∧(p→¬q) 是否为永真式、矛盾式或偶然式。",
        "options": "",
        "answer": "偶然式（等价于 ¬p）",
        "answer_cn": "偶然式。关键步骤：\n1. 列出 p,q 的 4 种赋值。\n2. 化简：(p→q)∧(p→¬q) ≡ (¬p∨q)∧(¬p∨¬q) ≡ ¬p∨(q∧¬q) ≡ ¬p。\n3. 故公式等价于 ¬p，当 p=F 时为真，p=T 时为假。\n4. 既非永真也非矛盾，故为偶然式。",
        "tags": "真值表,永真式,矛盾式",
    },
    {
        "chapter": "第1章", "section": "1.3", "question_type": "calc", "difficulty": "hard",
        "question_text": "求命题公式 p→(q→r) 的主合取范式。",
        "options": "",
        "answer": "主合取范式为 (¬p∨¬q∨r)（即最大项 M₆）",
        "answer_cn": "关键步骤：\n1. 化简：p→(q→r) ≡ p→(¬q∨r) ≡ ¬p∨¬q∨r。\n2. 该析取式仅在 p=T,q=T,r=F 时为假，对应最大项 M₆=(¬p∨¬q∨r)。\n3. 故主合取范式仅含 M₆，即 (¬p∨¬q∨r)。\n4. 等价地，主析取范式含其余 7 个最小项 m₀,m₁,m₂,m₃,m₄,m₅,m₇。",
        "tags": "主合取范式,最大项,范式",
    },
    {
        "chapter": "第1章", "section": "1.3", "question_type": "proof", "difficulty": "medium",
        "question_text": "证明：p→q ≡ ¬q→¬p（即原命题与逆否命题等价）。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "证明关键步骤：\n1. 左式：p→q ≡ ¬p∨q（条件转析取）。\n2. 右式：¬q→¬p ≡ ¬(¬q)∨¬p ≡ q∨¬p ≡ ¬p∨q（交换律）。\n3. 二者均为 ¬p∨q，故 p→q ≡ ¬q→¬p。证毕。",
        "tags": "逆否命题,等价证明",
    },
    {
        "chapter": "第1章", "section": "1.3", "question_type": "proof", "difficulty": "medium",
        "question_text": "证明德摩根律：¬(p∧q) ≡ ¬p∨¬q。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "证明关键步骤（真值表法）：\n1. 列出 p,q 的 4 种赋值组合。\n2. 对每种赋值计算 p∧q 的真值，再取否定得 ¬(p∧q)。\n3. 同时计算 ¬p∨¬q 的真值。\n4. 比较两列：四种赋值下两式真值均相同，故 ¬(p∧q) ≡ ¬p∨¬q。证毕。",
        "tags": "德摩根律,真值表证明",
    },
    {
        "chapter": "第1章", "section": "1.3", "question_type": "proof", "difficulty": "medium",
        "question_text": "证明分配律：p∨(q∧r) ≡ (p∨q)∧(p∨r)。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "证明关键步骤（真值表法）：\n1. 列出 p,q,r 的 8 种赋值组合。\n2. 当 p=T 时：左式 T∨(任何)=T，右式 (T)∧(T)=T，相等。\n3. 当 p=F 时：左式 F∨(q∧r)=q∧r，右式 (q)∧(r)=q∧r，相等。\n4. 故 8 种赋值下两式恒相等。证毕。",
        "tags": "分配律,真值表证明",
    },
    {
        "chapter": "第1章", "section": "1.3", "question_type": "proof", "difficulty": "medium",
        "question_text": "证明：¬(p→q) ≡ p∧¬q。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "证明关键步骤：\n1. 由 p→q ≡ ¬p∨q（条件转析取）。\n2. 两边取否定：¬(p→q) ≡ ¬(¬p∨q)。\n3. 应用德摩根律：¬(¬p∨q) ≡ ¬(¬p)∧¬q ≡ p∧¬q（双重否定律）。\n4. 故 ¬(p→q) ≡ p∧¬q。证毕。",
        "tags": "蕴含否定,德摩根律,等价证明",
    },
    {
        "chapter": "第1章", "section": "1.1", "question_type": "proof", "difficulty": "easy",
        "question_text": "证明：p↔q ≡ (p→q)∧(q→p)。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "证明关键步骤（真值表法）：\n1. 双条件 p↔q 当 p、q 同真假时为真，即 (T,T) 与 (F,F) 时为真。\n2. 计算 (p→q)∧(q→p)：(T,T)→T，(T,F)→F，(F,T)→F，(F,F)→T。\n3. 两式真值表完全相同，故 p↔q ≡ (p→q)∧(q→p)。证毕。",
        "tags": "双条件,等价证明",
    },
    {
        "chapter": "第1章", "section": "1.3", "question_type": "true_false", "difficulty": "easy",
        "question_text": "判断对错：原命题 p→q 与其逆命题 q→p 逻辑等价。",
        "options": "",
        "answer": "错",
        "answer_cn": "错。原命题 p→q 与其逆否命题 ¬q→¬p 等价；而逆命题 q→p 一般与原命题不等价。反例：设 p=“n 是 4 的倍数”，q=“n 是 2 的倍数”，则 p→q 恒真但 q→p 不恒真。",
        "tags": "逆命题,等价,逆否命题",
    },
    {
        "chapter": "第1章", "section": "1.1", "question_type": "true_false", "difficulty": "medium",
        "question_text": "判断对错：在命题逻辑中，当蕴含 p→q 的前件 p 为假时，称 p→q 为“空真”。",
        "options": "",
        "answer": "对",
        "answer_cn": "对。当 p 为假时，无论 q 真假，p→q 均定义为真，这一性质称为“空真”（vacuously true）。",
        "tags": "空真,蕴含",
    },
    {
        "chapter": "第1章", "section": "1.1", "question_type": "short_answer", "difficulty": "medium",
        "question_text": "写出蕴含命题 p→q 的四种相关命题（原命题、逆命题、否命题、逆否命题）并指出哪些之间等价。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "四种相关命题：\n1. 原命题：p→q\n2. 逆命题：q→p\n3. 否命题：¬p→¬q\n4. 逆否命题：¬q→¬p\n等价关系：\n- 原命题 p→q ≡ 逆否命题 ¬q→¬p\n- 逆命题 q→p ≡ 否命题 ¬p→¬q\n注：原命题与逆命题、否命题一般不等价。",
        "tags": "蕴含,四种命题,逆否命题",
    },

    # ===================== 第2章 集合与函数 (20题) =====================
    {
        "chapter": "第2章", "section": "2.1", "question_type": "choice", "difficulty": "easy",
        "question_text": "集合 A={1,2}，B={2,3}，则 A∩B = ?",
        "options": "A. {1,2,3}\nB. {2}\nC. {1,3}\nD. ∅",
        "answer": "B",
        "answer_cn": "B. {2}。交集 A∩B 是同时属于 A 和 B 的元素，仅 2 同时属于两集合。",
        "tags": "集合,交集",
    },
    {
        "chapter": "第2章", "section": "2.1", "question_type": "choice", "difficulty": "easy",
        "question_text": "集合 A={1,2,3}，B={2,3,4}，则 A∪B = ?",
        "options": "A. {2,3}\nB. {1,4}\nC. {1,2,3,4}\nD. ∅",
        "answer": "C",
        "answer_cn": "C. {1,2,3,4}。并集 A∪B 是属于 A 或属于 B 的所有元素。",
        "tags": "集合,并集",
    },
    {
        "chapter": "第2章", "section": "2.1", "question_type": "choice", "difficulty": "easy",
        "question_text": "集合 A={1,2,3}，B={2,3,4}，则 A−B = ?",
        "options": "A. {1}\nB. {4}\nC. {1,4}\nD. {2,3}",
        "answer": "A",
        "answer_cn": "A. {1}。差集 A−B 是属于 A 但不属于 B 的元素，故 {1}。",
        "tags": "集合,差集",
    },
    {
        "chapter": "第2章", "section": "2.1", "question_type": "choice", "difficulty": "medium",
        "question_text": "全集 U={1,2,3,4}，A={1,2}，则 A 的补集 A¯ = ?",
        "options": "A. {1,2}\nB. {3,4}\nC. {1,2,3,4}\nD. ∅",
        "answer": "B",
        "answer_cn": "B. {3,4}。补集 A¯ = U−A = {1,2,3,4}−{1,2} = {3,4}。",
        "tags": "集合,补集",
    },
    {
        "chapter": "第2章", "section": "2.1", "question_type": "choice", "difficulty": "medium",
        "question_text": "集合 A={1,2}，B={a,b}，则 A×B 的元素个数为？",
        "options": "A. 2\nB. 4\nC. 6\nD. 8",
        "answer": "B",
        "answer_cn": "B. 4。笛卡尔积 A×B 的元素个数为 |A|×|B| = 2×2 = 4，即 {(1,a),(1,b),(2,a),(2,b)}。",
        "tags": "笛卡尔积,集合",
    },
    {
        "chapter": "第2章", "section": "2.3", "question_type": "choice", "difficulty": "medium",
        "question_text": "函数 f:R→R, f(x)=x² 的性质是？",
        "options": "A. 单射且满射\nB. 单射不满射\nC. 满射不单射\nD. 既不单射也不满射",
        "answer": "D",
        "answer_cn": "D. 既不单射也不满射。f(1)=f(−1)=1 故不单射；f(R)=[0,∞)≠R 故不满射。",
        "tags": "函数,单射,满射",
    },
    {
        "chapter": "第2章", "section": "2.3", "question_type": "choice", "difficulty": "easy",
        "question_text": "函数 f:R→R, f(x)=2x+1 是？",
        "options": "A. 单射不满射\nB. 满射不单射\nC. 双射\nD. 既不单射也不满射",
        "answer": "C",
        "answer_cn": "C. 双射。f(x)=2x+1 严格单调递增，故单射；又对任意 y∈R，x=(y−1)/2 使 f(x)=y，故满射。因此是双射。",
        "tags": "函数,双射,单射,满射",
    },
    {
        "chapter": "第2章", "section": "2.5", "question_type": "choice", "difficulty": "medium",
        "question_text": "若 |A|=m，|B|=n，则从 A 到 B 的函数共有多少个？",
        "options": "A. m+n\nB. m·n\nC. n^m\nD. m^n",
        "answer": "C",
        "answer_cn": "C. n^m。A 中每个元素（共 m 个）映射到 B 的方式有 n 种，故共有 n^m 个函数。",
        "tags": "函数计数,集合",
    },
    {
        "chapter": "第2章", "section": "2.1", "question_type": "choice", "difficulty": "hard",
        "question_text": "集合 A 的幂集 P(A) 在 |A|=n 时的元素个数为？",
        "options": "A. n\nB. 2n\nC. 2ⁿ\nD. n²",
        "answer": "C",
        "answer_cn": "C. 2ⁿ。幂集 P(A) 是 A 的所有子集构成的集合，每个元素有“属于/不属于”两种选择，共 2ⁿ 个子集。",
        "tags": "幂集,子集",
    },
    {
        "chapter": "第2章", "section": "2.1", "question_type": "fill", "difficulty": "easy",
        "question_text": "空集 ∅ 的元素个数为____，其幂集 P(∅) 的元素个数为____。",
        "options": "",
        "answer": "0；1",
        "answer_cn": "0；1。空集 ∅ 没有元素，故元素个数为 0；P(∅)={∅}，仅含空集自身，元素个数为 1=2⁰。",
        "tags": "空集,幂集",
    },
    {
        "chapter": "第2章", "section": "2.1", "question_type": "fill", "difficulty": "easy",
        "question_text": "设 A={1,2,3}，则 |P(A)|=____。",
        "options": "",
        "answer": "8",
        "answer_cn": "8。|P(A)|=2^|A|=2³=8。",
        "tags": "幂集,集合",
    },
    {
        "chapter": "第2章", "section": "2.3", "question_type": "fill", "difficulty": "medium",
        "question_text": "若 f:A→B 既是单射又是满射，则称 f 为____。",
        "options": "",
        "answer": "双射（一一对应）",
        "answer_cn": "双射（一一对应）。同时满足单射和满射的函数称为双射，此时存在逆函数 f⁻¹:B→A。",
        "tags": "双射,单射,满射",
    },
    {
        "chapter": "第2章", "section": "2.3", "question_type": "fill", "difficulty": "medium",
        "question_text": "函数 f(x)=x³ 在 R→R 上是____函数（填单射/满射/双射之一）。",
        "options": "",
        "answer": "双射",
        "answer_cn": "双射。f(x)=x³ 严格单调递增故单射；又对任意 y∈R，x=∛y 使 f(x)=y 故满射，因此是双射。",
        "tags": "双射,函数",
    },
    {
        "chapter": "第2章", "section": "2.1", "question_type": "calc", "difficulty": "medium",
        "question_text": "设 A={1,2,3,4}，B={2,4,6}，C={1,2,4}，求 (A∩B)∪(B−C)。",
        "options": "",
        "answer": "{2,4,6}",
        "answer_cn": "关键步骤：\n1. A∩B = {2,4}（A 与 B 共有元素）。\n2. B−C = {6}（属于 B 不属于 C 的元素，2、4 都在 C 中）。\n3. (A∩B)∪(B−C) = {2,4}∪{6} = {2,4,6}。",
        "tags": "集合运算,交集,并集,差集",
    },
    {
        "chapter": "第2章", "section": "2.1", "question_type": "calc", "difficulty": "medium",
        "question_text": "集合 A={a,b}，求 A×A 的所有元素及 |A×A|。",
        "options": "",
        "answer": "{(a,a),(a,b),(b,a),(b,b)}，共4个",
        "answer_cn": "关键步骤：\n1. A×A = {(x,y) | x∈A, y∈A}。\n2. 列举所有组合：第一个分量取 a 或 b，第二个分量取 a 或 b。\n3. A×A = {(a,a),(a,b),(b,a),(b,b)}。\n4. |A×A| = |A|×|A| = 2×2 = 4。",
        "tags": "笛卡尔积,集合",
    },
    {
        "chapter": "第2章", "section": "2.3", "question_type": "calc", "difficulty": "hard",
        "question_text": "判断函数 f:Z→Z, f(x)=3x+1 是否为单射、满射、双射，并说明理由。",
        "options": "",
        "answer": "单射但不满射，故非双射",
        "answer_cn": "关键步骤：\n1. 单射性：若 f(a)=f(b)，即 3a+1=3b+1，得 a=b，故 f 单射。\n2. 满射性：取 y=0∈Z，则需 3x+1=0，即 x=−1/3∉Z，不存在整数 x 使 f(x)=0，故 f 不满射。\n3. 结论：f 单射但不满射，因此不是双射。",
        "tags": "函数,单射,满射,双射",
    },
    {
        "chapter": "第2章", "section": "2.1", "question_type": "proof", "difficulty": "medium",
        "question_text": "证明：A∪(B∩C) = (A∪B)∩(A∪C)（集合的分配律）。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "证明关键步骤（互含法）：\n1. 证左⊆右：设 x∈A∪(B∩C)。若 x∈A，则 x∈A∪B 且 x∈A∪C，故 x∈(A∪B)∩(A∪C)。若 x∈B∩C，则 x∈B 故 x∈A∪B，且 x∈C 故 x∈A∪C，从而 x∈(A∪B)∩(A∪C)。\n2. 证右⊆左：设 x∈(A∪B)∩(A∪C)。若 x∈A，则 x∈A∪(B∩C)。若 x∉A，则由 x∈A∪B 得 x∈B，由 x∈A∪C 得 x∈C，故 x∈B∩C，从而 x∈A∪(B∩C)。\n3. 两边互含，故 A∪(B∩C) = (A∪B)∩(A∪C)。证毕。",
        "tags": "集合,分配律,证明",
    },
    {
        "chapter": "第2章", "section": "2.3", "question_type": "true_false", "difficulty": "easy",
        "question_text": "判断对错：若 f:A→B 是双射，则存在逆函数 f⁻¹:B→A 且 f⁻¹ 也是双射。",
        "options": "",
        "answer": "对",
        "answer_cn": "对。双射 f 存在逆函数 f⁻¹:B→A，且 f⁻¹ 也是双射，满足 f∘f⁻¹=id_B 和 f⁻¹∘f=id_A。",
        "tags": "双射,逆函数",
    },
    {
        "chapter": "第2章", "section": "2.3", "question_type": "short_answer", "difficulty": "medium",
        "question_text": "简述单射、满射、双射的定义，并各举一例。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "定义：\n1. 单射（injection）：若 f(x₁)=f(x₂) 则 x₁=x₂，即不同输入对应不同输出。例：f:R→R, f(x)=x² 在 [0,∞) 上单射。\n2. 满射（surjection）：对任意 y∈B，存在 x∈A 使 f(x)=y。例：f:R→[0,∞), f(x)=x² 满射。\n3. 双射（bijection）：既是单射又是满射，也称一一对应。例：f:R→R, f(x)=2x+1 双射。",
        "tags": "函数,单射,满射,双射",
    },
    {
        "chapter": "第2章", "section": "2.1", "question_type": "short_answer", "difficulty": "easy",
        "question_text": "简述幂集的概念，并求集合 A={1,2} 的幂集。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "幂集 P(A) 是 A 的所有子集构成的集合。\n对于 A={1,2}：\nP(A) = {∅, {1}, {2}, {1,2}}\n共 2²=4 个元素。",
        "tags": "幂集,子集",
    },

    # ===================== 第3章 算法 (12题) =====================
    {
        "chapter": "第3章", "section": "3.1", "question_type": "choice", "difficulty": "easy",
        "question_text": "算法必须具备的性质不包括以下哪一项？",
        "options": "A. 有限性\nB. 确定性\nC. 不可更改性\nD. 通用性",
        "answer": "C",
        "answer_cn": "C. 不可更改性。算法的基本性质包括：有限性、确定性、输入输出、可行性、通用性。算法可以修改优化，不属于必要性质。",
        "tags": "算法,性质",
    },
    {
        "chapter": "第3章", "section": "3.2", "question_type": "choice", "difficulty": "medium",
        "question_text": "线性查找算法在最坏情况下的时间复杂度为？（n为数据规模）",
        "options": "A. O(1)\nB. O(log n)\nC. O(n)\nD. O(n²)",
        "answer": "C",
        "answer_cn": "C. O(n)。线性查找最坏情况需遍历整个数组，比较 n 次，时间复杂度 O(n)。",
        "tags": "算法,时间复杂度,线性查找",
    },
    {
        "chapter": "第3章", "section": "3.2", "question_type": "choice", "difficulty": "medium",
        "question_text": "二分查找算法的时间复杂度为？（n为有序数据规模）",
        "options": "A. O(1)\nB. O(log n)\nC. O(n)\nD. O(n log n)",
        "answer": "B",
        "answer_cn": "B. O(log n)。二分查找每次将搜索区间减半，最多比较 ⌈log₂n⌉+1 次，时间复杂度 O(log n)。",
        "tags": "算法,二分查找,时间复杂度",
    },
    {
        "chapter": "第3章", "section": "3.3", "question_type": "choice", "difficulty": "easy",
        "question_text": "冒泡排序算法的平均时间复杂度为？",
        "options": "A. O(n)\nB. O(n log n)\nC. O(n²)\nD. O(n³)",
        "answer": "C",
        "answer_cn": "C. O(n²)。冒泡排序使用两层嵌套循环，平均和最坏情况下比较次数为 n(n−1)/2，时间复杂度 O(n²)。",
        "tags": "算法,排序,时间复杂度",
    },
    {
        "chapter": "第3章", "section": "3.4", "question_type": "choice", "difficulty": "hard",
        "question_text": "欧几里得算法求 gcd(a,b) 的时间复杂度为？（设 a,b 位数分别为 m,n）",
        "options": "A. O(log(a+b))\nB. O(a+b)\nC. O(a·b)\nD. O(2ⁿ)",
        "answer": "A",
        "answer_cn": "A. O(log(a+b))。欧几里得算法每步余数至少减半，迭代次数不超过 2⌈log₂(a+b)⌉，时间复杂度 O(log(a+b))。",
        "tags": "欧几里得算法,时间复杂度,gcd",
    },
    {
        "chapter": "第3章", "section": "3.1", "question_type": "fill", "difficulty": "easy",
        "question_text": "算法在执行有限步骤后必须终止的性质称为____。",
        "options": "",
        "answer": "有限性（终止性）",
        "answer_cn": "有限性（终止性）。算法必须在执行有限步后终止并给出结果，这是算法的基本性质之一。",
        "tags": "算法,有限性",
    },
    {
        "chapter": "第3章", "section": "3.2", "question_type": "fill", "difficulty": "medium",
        "question_text": "二分查找算法要求数据必须____。",
        "options": "",
        "answer": "有序（已排序）",
        "answer_cn": "有序（已排序）。二分查找基于中间元素与目标比较，要求数据预先按升序或降序排列，否则无法正确实施。",
        "tags": "二分查找,有序",
    },
    {
        "chapter": "第3章", "section": "3.4", "question_type": "calc", "difficulty": "medium",
        "question_text": "用欧几里得算法求 gcd(252, 198)，写出每一步。",
        "options": "",
        "answer": "gcd(252,198)=18",
        "answer_cn": "关键步骤：\n1. 252 = 198×1 + 54\n2. 198 = 54×3 + 36\n3. 54 = 36×1 + 18\n4. 36 = 18×2 + 0\n5. 余数为 0，故 gcd(252,198)=18。",
        "tags": "欧几里得算法,gcd,计算",
    },
    {
        "chapter": "第3章", "section": "3.4", "question_type": "calc", "difficulty": "medium",
        "question_text": "用辗转相除法求 gcd(1071, 462)。",
        "options": "",
        "answer": "gcd(1071,462)=21",
        "answer_cn": "关键步骤：\n1. 1071 = 462×2 + 147\n2. 462 = 147×3 + 21\n3. 147 = 21×7 + 0\n4. 余数为 0，故 gcd(1071,462)=21。",
        "tags": "欧几里得算法,gcd,计算",
    },
    {
        "chapter": "第3章", "section": "3.2", "question_type": "calc", "difficulty": "hard",
        "question_text": "对有序数组 [1,3,5,7,9,11,13] 使用二分查找目标 9，写出每步比较过程。",
        "options": "",
        "answer": "找到，索引为4（0-based）",
        "answer_cn": "关键步骤（下标从0计）：\n1. 初始 low=0, high=6, mid=3，A[3]=7 < 9，更新 low=4。\n2. low=4, high=6, mid=5，A[5]=11 > 9，更新 high=4。\n3. low=4, high=4, mid=4，A[4]=9 = 9，查找成功，返回索引 4。\n共比较 3 次。",
        "tags": "二分查找,算法过程",
    },
    {
        "chapter": "第3章", "section": "3.1", "question_type": "true_false", "difficulty": "easy",
        "question_text": "判断对错：算法的每一步必须有明确定义，不能有二义性。",
        "options": "",
        "answer": "对",
        "answer_cn": "对。确定性要求算法每一步操作必须明确无歧义，这是算法的基本性质之一。",
        "tags": "算法,确定性",
    },
    {
        "chapter": "第3章", "section": "3.2", "question_type": "short_answer", "difficulty": "medium",
        "question_text": "简述线性查找与二分查找的区别及适用场景。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "区别：\n1. 线性查找：依次比较每个元素，无需数据有序，时间复杂度 O(n)。适用于无序数据或规模小的数据。\n2. 二分查找：每次取中点比较，要求数据有序，时间复杂度 O(log n)。适用于大规模有序数据。\n适用场景：数据有序且规模大时优先用二分查找；数据无序或频繁插入删除时不适用。",
        "tags": "线性查找,二分查找,算法对比",
    },

    # ===================== 第4章 数论与密码学 (15题) =====================
    {
        "chapter": "第4章", "section": "4.1", "question_type": "choice", "difficulty": "easy",
        "question_text": "17 mod 5 的结果是？",
        "options": "A. 1\nB. 2\nC. 3\nD. 4",
        "answer": "B",
        "answer_cn": "B. 2。17 = 5×3 + 2，故 17 mod 5 = 2。",
        "tags": "模运算,数论",
    },
    {
        "chapter": "第4章", "section": "4.1", "question_type": "choice", "difficulty": "easy",
        "question_text": "下列哪个数是素数？",
        "options": "A. 9\nB. 15\nC. 17\nD. 21",
        "answer": "C",
        "answer_cn": "C. 17。17 只能被 1 和 17 整除，是素数。9=3²，15=3×5，21=3×7 均为合数。",
        "tags": "素数,数论",
    },
    {
        "chapter": "第4章", "section": "4.1", "question_type": "choice", "difficulty": "medium",
        "question_text": "gcd(12, 18) = ?",
        "options": "A. 2\nB. 3\nC. 6\nD. 12",
        "answer": "C",
        "answer_cn": "C. 6。12=2²×3，18=2×3²，公约数为 2×3=6。",
        "tags": "gcd,数论",
    },
    {
        "chapter": "第4章", "section": "4.1", "question_type": "choice", "difficulty": "medium",
        "question_text": "lcm(4, 6) = ?",
        "options": "A. 2\nB. 10\nC. 12\nD. 24",
        "answer": "C",
        "answer_cn": "C. 12。lcm(4,6)=4×6/gcd(4,6)=24/2=12。",
        "tags": "lcm,数论",
    },
    {
        "chapter": "第4章", "section": "4.3", "question_type": "choice", "difficulty": "medium",
        "question_text": "模 7 下 3 的乘法逆元是？",
        "options": "A. 2\nB. 3\nC. 5\nD. 6",
        "answer": "C",
        "answer_cn": "C. 5。3×5=15≡1 (mod 7)，故 5 是 3 在模 7 下的乘法逆元。",
        "tags": "模逆元,数论",
    },
    {
        "chapter": "第4章", "section": "4.6", "question_type": "choice", "difficulty": "hard",
        "question_text": "RSA 密码体制的安全性主要基于哪个数学难题？",
        "options": "A. 大整数分解困难\nB. 离散对数困难\nC. 子集和问题\nD. 背包问题",
        "answer": "A",
        "answer_cn": "A. 大整数分解困难。RSA 利用大素数 p、q 乘积 n=pq 易求，但由 n 反推 p、q 困难这一特性保证安全。",
        "tags": "RSA,密码学,大整数分解",
    },
    {
        "chapter": "第4章", "section": "4.3", "question_type": "choice", "difficulty": "medium",
        "question_text": "费马小定理：若 p 为素数且 gcd(a,p)=1，则 a^(p−1) mod p = ?",
        "options": "A. 0\nB. 1\nC. a\nD. p−1",
        "answer": "B",
        "answer_cn": "B. 1。费马小定理：a^(p−1) ≡ 1 (mod p)，其中 p 为素数且 a 不被 p 整除。",
        "tags": "费马小定理,数论",
    },
    {
        "chapter": "第4章", "section": "4.1", "question_type": "fill", "difficulty": "easy",
        "question_text": "若 a mod n = b mod n，则记作 a ____ b (mod n)。",
        "options": "",
        "answer": "≡",
        "answer_cn": "≡。a 与 b 模 n 同余记作 a ≡ b (mod n)，等价于 n | (a−b)。",
        "tags": "同余,模运算",
    },
    {
        "chapter": "第4章", "section": "4.1", "question_type": "fill", "difficulty": "medium",
        "question_text": "算术基本定理指出：每个大于1的整数都可唯一分解为____的乘积。",
        "options": "",
        "answer": "素数（素因子）",
        "answer_cn": "素数（素因子）。算术基本定理（唯一分解定理）：每个大于 1 的正整数可唯一分解为素数的乘积（不计顺序）。",
        "tags": "算术基本定理,素数分解",
    },
    {
        "chapter": "第4章", "section": "4.3", "question_type": "fill", "difficulty": "medium",
        "question_text": "若 a·b ≡ 1 (mod n)，则称 b 是 a 模 n 的____。",
        "options": "",
        "answer": "乘法逆元",
        "answer_cn": "乘法逆元。a 模 n 的乘法逆元 b 满足 a·b ≡ 1 (mod n)，存在当且仅当 gcd(a,n)=1。",
        "tags": "模逆元,同余",
    },
    {
        "chapter": "第4章", "section": "4.1", "question_type": "calc", "difficulty": "medium",
        "question_text": "求 7^100 mod 13。",
        "options": "",
        "answer": "9",
        "answer_cn": "关键步骤（用费马小定理）：\n1. 由费马小定理，7^12 ≡ 1 (mod 13)（13 为素数，gcd(7,13)=1）。\n2. 100 = 12×8 + 4，故 7^100 = (7^12)^8 × 7^4 ≡ 1^8 × 7^4 (mod 13)。\n3. 7² = 49 ≡ 49−3×13 = 49−39 = 10 (mod 13)。\n4. 7⁴ = (7²)² ≡ 10² = 100 ≡ 100−7×13 = 100−91 = 9 (mod 13)。\n5. 故 7^100 mod 13 = 9。",
        "tags": "费马小定理,模运算,计算",
    },
    {
        "chapter": "第4章", "section": "4.3", "question_type": "calc", "difficulty": "hard",
        "question_text": "用扩展欧几里得算法求 3 模 7 的乘法逆元。",
        "options": "",
        "answer": "5",
        "answer_cn": "关键步骤：\n1. 用欧几里得算法：7=3×2+1，3=1×3+0，gcd=1。\n2. 回代：1 = 7−3×2 = 7−2×3。\n3. 即 1 = (−2)×3 + 1×7，故 3 的逆元为 −2 ≡ 5 (mod 7)。\n4. 验证：3×5=15=7×2+1 ≡ 1 (mod 7)。故 3⁻¹ ≡ 5 (mod 7)。",
        "tags": "扩展欧几里得算法,模逆元",
    },
    {
        "chapter": "第4章", "section": "4.1", "question_type": "proof", "difficulty": "medium",
        "question_text": "证明：若 a ≡ b (mod n) 且 c ≡ d (mod n)，则 a+c ≡ b+d (mod n)。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "证明关键步骤：\n1. 由 a ≡ b (mod n)，存在整数 k₁ 使 a−b = k₁·n。\n2. 由 c ≡ d (mod n)，存在整数 k₂ 使 c−d = k₂·n。\n3. 两式相加：(a+c)−(b+d) = (a−b)+(c−d) = k₁·n+k₂·n = (k₁+k₂)·n。\n4. 故 (a+c)−(b+d) 是 n 的倍数，即 a+c ≡ b+d (mod n)。证毕。",
        "tags": "同余,模运算,证明",
    },
    {
        "chapter": "第4章", "section": "4.1", "question_type": "true_false", "difficulty": "easy",
        "question_text": "判断对错：1 不是素数。",
        "options": "",
        "answer": "对",
        "answer_cn": "对。素数定义为大于 1 且只能被 1 和自身整除的正整数，1 不满足“大于1”条件，故 1 不是素数。",
        "tags": "素数,定义",
    },
    {
        "chapter": "第4章", "section": "4.6", "question_type": "short_answer", "difficulty": "medium",
        "question_text": "简述 RSA 密码体制中公钥与私钥的生成步骤。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "RSA 密钥生成步骤：\n1. 选取两个大素数 p、q，计算 n=p·q。\n2. 计算 φ(n)=(p−1)(q−1)（欧拉函数）。\n3. 选取加密指数 e，满足 1<e<φ(n) 且 gcd(e,φ(n))=1，通常取 e=65537。\n4. 计算解密指数 d，使 d·e ≡ 1 (mod φ(n))，即 d 是 e 模 φ(n) 的逆元。\n5. 公钥为 (e, n)，私钥为 (d, n)。加密：c=m^e mod n；解密：m=c^d mod n。",
        "tags": "RSA,密码学,密钥生成",
    },

    # ===================== 第5章 归纳与递归 (12题) =====================
    {
        "chapter": "第5章", "section": "5.1", "question_type": "choice", "difficulty": "easy",
        "question_text": "数学归纳法证明对全体正整数 n 成立时，第一步（基础步）应证明？",
        "options": "A. n=0 时命题成立\nB. n=1 时命题成立\nC. n=k 时命题成立\nD. n→∞ 时命题成立",
        "answer": "B",
        "answer_cn": "B. n=1 时命题成立。数学归纳法证明对全体正整数 n 成立，第一步是验证初始值 n=1 时命题成立（若包含 0 则验证 n=0）。",
        "tags": "数学归纳法,基础步",
    },
    {
        "chapter": "第5章", "section": "5.1", "question_type": "choice", "difficulty": "medium",
        "question_text": "第二数学归纳法（强归纳法）的归纳假设是？",
        "options": "A. 假设 n=k 时成立\nB. 假设 n≤k 时均成立\nC. 假设 n=k+1 时成立\nD. 假设 n≥k 时成立",
        "answer": "B",
        "answer_cn": "B. 假设 n≤k 时均成立。强归纳法假设对所有不超过 k 的正整数命题均成立，从而推导 n=k+1 时成立。",
        "tags": "强归纳法,数学归纳法",
    },
    {
        "chapter": "第5章", "section": "5.3", "question_type": "choice", "difficulty": "medium",
        "question_text": "斐波那契数列 F(n) 满足 F(1)=F(2)=1, F(n)=F(n−1)+F(n−2)，则 F(6) = ?",
        "options": "A. 5\nB. 8\nC. 13\nD. 21",
        "answer": "B",
        "answer_cn": "B. 8。F(1)=1,F(2)=1,F(3)=2,F(4)=3,F(5)=5,F(6)=8。",
        "tags": "递归,斐波那契数列",
    },
    {
        "chapter": "第5章", "section": "5.1", "question_type": "choice", "difficulty": "hard",
        "question_text": "用数学归纳法证明 1+2+…+n = n(n+1)/2 时，归纳步由 P(k) 推 P(k+1) 需证明 P(k+1) 等于？",
        "options": "A. k(k+1)/2\nB. (k+1)(k+2)/2\nC. k(k−1)/2\nD. (k+1)²/2",
        "answer": "B",
        "answer_cn": "B. (k+1)(k+2)/2。归纳步需证明 1+2+…+k+(k+1) = k(k+1)/2+(k+1) = (k+1)(k/2+1) = (k+1)(k+2)/2。",
        "tags": "数学归纳法,求和公式",
    },
    {
        "chapter": "第5章", "section": "5.1", "question_type": "fill", "difficulty": "easy",
        "question_text": "数学归纳法的两个基本步骤是____和____。",
        "options": "",
        "answer": "基础步；归纳步",
        "answer_cn": "基础步；归纳步。基础步验证初始值（如 n=1）成立；归纳步假设 n=k 成立推导 n=k+1 成立。",
        "tags": "数学归纳法,步骤",
    },
    {
        "chapter": "第5章", "section": "5.3", "question_type": "fill", "difficulty": "medium",
        "question_text": "递归定义的阶乘函数 f(n)=n! 的递归关系为 f(n)=____，基础情形 f(0)=____。",
        "options": "",
        "answer": "n·f(n−1)；1",
        "answer_cn": "n·f(n−1)；1。阶乘递归定义：f(0)=1，f(n)=n·f(n−1) (n≥1)。",
        "tags": "递归,阶乘",
    },
    {
        "chapter": "第5章", "section": "5.1", "question_type": "calc", "difficulty": "medium",
        "question_text": "用数学归纳法证明 1+3+5+…+(2n−1) = n² 的归纳步骤。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "关键步骤：\n1. 基础步：n=1 时左边=1，右边=1²=1，成立。\n2. 归纳假设：设 n=k 时 1+3+…+(2k−1) = k² 成立。\n3. 归纳步：n=k+1 时，左边 = k² + (2k+1) = (k+1)² = 右边，成立。\n4. 由数学归纳法，对所有正整数 n 成立。证毕。",
        "tags": "数学归纳法,奇数求和",
    },
    {
        "chapter": "第5章", "section": "5.3", "question_type": "calc", "difficulty": "medium",
        "question_text": "已知递归关系 T(n)=2T(n−1)+1, T(0)=0，求 T(4)。",
        "options": "",
        "answer": "T(4)=15",
        "answer_cn": "关键步骤：\n1. T(0)=0\n2. T(1)=2×0+1=1\n3. T(2)=2×1+1=3\n4. T(3)=2×3+1=7\n5. T(4)=2×7+1=15\n故 T(4)=15。",
        "tags": "递归关系,计算",
    },
    {
        "chapter": "第5章", "section": "5.2", "question_type": "calc", "difficulty": "hard",
        "question_text": "用数学归纳法证明 2^n ≥ n² 对所有 n≥4 成立的归纳步骤。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "关键步骤：\n1. 基础步：n=4 时 2⁴=16 ≥ 4²=16，成立。\n2. 归纳假设：设 2^k ≥ k² 对某 k≥4 成立。\n3. 归纳步：2^(k+1) = 2·2^k ≥ 2k²；需证 2k² ≥ (k+1)²，即 k²−2k−1 ≥ 0。当 k≥3 时 (k−1)²−2 ≥ 2 > 0，成立。\n4. 由数学归纳法，2^n ≥ n² 对所有 n≥4 成立。证毕。",
        "tags": "数学归纳法,不等式证明",
    },
    {
        "chapter": "第5章", "section": "5.1", "question_type": "proof", "difficulty": "medium",
        "question_text": "用数学归纳法证明：1+2+…+n = n(n+1)/2 对所有正整数 n 成立。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "证明关键步骤：\n1. 基础步：n=1 时左边=1，右边=1×2/2=1，成立。\n2. 归纳假设：设 n=k 时 1+2+…+k = k(k+1)/2 成立。\n3. 归纳步：n=k+1 时，左边 = k(k+1)/2+(k+1) = (k+1)(k+2)/2 = 右边，成立。\n4. 由数学归纳法，对所有正整数 n 成立。证毕。",
        "tags": "数学归纳法,求和",
    },
    {
        "chapter": "第5章", "section": "5.1", "question_type": "proof", "difficulty": "hard",
        "question_text": "用数学归纳法证明：n³−n 能被 6 整除对所有正整数 n 成立。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "证明关键步骤：\n1. 基础步：n=1 时 1³−1=0=6×0，能被 6 整除。\n2. 归纳假设：设 k³−k = 6m。\n3. 归纳步：(k+1)³−(k+1) = (k³−k)+3k(k+1) = 6m+6t（k(k+1) 为偶数 =2t），故能被 6 整除。\n4. 由数学归纳法，对所有正整数 n 成立。证毕。",
        "tags": "数学归纳法,整除,证明",
    },
    {
        "chapter": "第5章", "section": "5.3", "question_type": "short_answer", "difficulty": "medium",
        "question_text": "简述递归定义的两大要素，并说明缺少任一要素可能产生的问题。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "递归定义两大要素：\n1. 基础情形（base case）：明确定义最小输入的值，作为递归终止条件。\n2. 递归规则（recursive rule）：用较小规模的结果定义当前规模的结果。\n缺少任一要素的问题：\n- 缺基础情形：递归无限进行，无法终止，导致栈溢出。\n- 缺递归规则：无法由已知推导未知，定义不完整。",
        "tags": "递归,基础情形,递归规则",
    },

    # ===================== 第6章 计数 (18题) =====================
    {
        "chapter": "第6章", "section": "6.1", "question_type": "choice", "difficulty": "easy",
        "question_text": "从 5 个不同元素中任取 2 个的排列数 P(5,2) = ?",
        "options": "A. 10\nB. 20\nC. 25\nD. 60",
        "answer": "B",
        "answer_cn": "B. 20。P(5,2) = 5×4 = 20。",
        "tags": "排列,计数",
    },
    {
        "chapter": "第6章", "section": "6.1", "question_type": "choice", "difficulty": "easy",
        "question_text": "从 5 个不同元素中任取 2 个的组合数 C(5,2) = ?",
        "options": "A. 10\nB. 20\nC. 25\nD. 5",
        "answer": "A",
        "answer_cn": "A. 10。C(5,2) = 5!/(2!·3!) = (5×4)/(2×1) = 10。",
        "tags": "组合,计数",
    },
    {
        "chapter": "第6章", "section": "6.1", "question_type": "choice", "difficulty": "medium",
        "question_text": "5 本不同的书排成一排，共有多少种排法？",
        "options": "A. 25\nB. 60\nC. 120\nD. 720",
        "answer": "C",
        "answer_cn": "C. 120。5 个不同元素的全排列 = 5! = 120。",
        "tags": "排列,全排列",
    },
    {
        "chapter": "第6章", "section": "6.3", "question_type": "choice", "difficulty": "medium",
        "question_text": "鸽巢原理：将 10 只鸽子放入 9 个鸽巢，至少有一个鸽巢中有多少只鸽子？",
        "options": "A. 1\nB. 2\nC. 3\nD. 5",
        "answer": "B",
        "answer_cn": "B. 2。由鸽巢原理，将 n+1 个物体放入 n 个盒子，至少有一个盒子含至少 2 个物体。10>9，故至少有 1 个鸽巢含 2 只。",
        "tags": "鸽巢原理,计数",
    },
    {
        "chapter": "第6章", "section": "6.4", "question_type": "choice", "difficulty": "medium",
        "question_text": "二项式系数 C(6,3) = ?",
        "options": "A. 15\nB. 20\nC. 30\nD. 60",
        "answer": "B",
        "answer_cn": "B. 20。C(6,3) = 6!/(3!·3!) = (6×5×4)/(3×2×1) = 20。",
        "tags": "二项式系数,组合",
    },
    {
        "chapter": "第6章", "section": "6.4", "question_type": "choice", "difficulty": "medium",
        "question_text": "(x+y)⁴ 展开式中 x²y² 的系数是？",
        "options": "A. 4\nB. 6\nC. 8\nD. 12",
        "answer": "B",
        "answer_cn": "B. 6。由二项式定理，x²y² 的系数为 C(4,2)=6。",
        "tags": "二项式定理,展开",
    },
    {
        "chapter": "第6章", "section": "6.5", "question_type": "choice", "difficulty": "hard",
        "question_text": "方程 x₁+x₂+x₃=10 的非负整数解的个数是？",
        "options": "A. 36\nB. 55\nC. 66\nD. 120",
        "answer": "C",
        "answer_cn": "C. 66。由“星与条”方法，x₁+x₂+x₃=10 的非负整数解数为 C(10+3−1, 3−1) = C(12,2) = 66。",
        "tags": "星与条,组合,计数",
    },
    {
        "chapter": "第6章", "section": "6.6", "question_type": "choice", "difficulty": "hard",
        "question_text": "在 1 到 100 的整数中，能被 3 或 5 整除的整数有多少个？",
        "options": "A. 33\nB. 47\nC. 53\nD. 60",
        "answer": "B",
        "answer_cn": "B. 47。由容斥：|A|=⌊100/3⌋=33，|B|=⌊100/5⌋=20，|A∩B|=⌊100/15⌋=6，故 |A∪B|=33+20−6=47。",
        "tags": "容斥原理,计数",
    },
    {
        "chapter": "第6章", "section": "6.1", "question_type": "fill", "difficulty": "easy",
        "question_text": "n 个不同元素的全排列数为____。",
        "options": "",
        "answer": "n!",
        "answer_cn": "n!。n 个不同元素的全排列数为 n! = n×(n−1)×…×1。",
        "tags": "全排列,阶乘",
    },
    {
        "chapter": "第6章", "section": "6.1", "question_type": "fill", "difficulty": "medium",
        "question_text": "排列数公式 P(n,r) = ____。",
        "options": "",
        "answer": "n!/(n−r)!",
        "answer_cn": "n!/(n−r)!。从 n 个不同元素取 r 个的排列数 P(n,r) = n!/(n−r)!。",
        "tags": "排列,公式",
    },
    {
        "chapter": "第6章", "section": "6.1", "question_type": "fill", "difficulty": "medium",
        "question_text": "组合数公式 C(n,r) = ____。",
        "options": "",
        "answer": "n!/(r!·(n−r)!)",
        "answer_cn": "n!/(r!·(n−r)!)。从 n 个不同元素取 r 个的组合数 C(n,r) = n!/(r!·(n−r)!)。",
        "tags": "组合,公式",
    },
    {
        "chapter": "第6章", "section": "6.4", "question_type": "fill", "difficulty": "hard",
        "question_text": "二项式定理公式 (x+y)ⁿ = ____。",
        "options": "",
        "answer": "Σ_{k=0}^{n} C(n,k) x^{n−k} y^k",
        "answer_cn": "Σ_{k=0}^{n} C(n,k) x^{n−k} y^k。二项式定理将 (x+y)ⁿ 展开为各二项式系数 C(n,k) 与对应 x、y 幂的乘积之和。",
        "tags": "二项式定理,公式",
    },
    {
        "chapter": "第6章", "section": "6.1", "question_type": "calc", "difficulty": "medium",
        "question_text": "计算 C(8,3) 与 P(8,3)。",
        "options": "",
        "answer": "C(8,3)=56, P(8,3)=336",
        "answer_cn": "关键步骤：\n1. P(8,3) = 8×7×6 = 336。\n2. C(8,3) = P(8,3)/3! = 336/6 = 56。",
        "tags": "排列,组合,计算",
    },
    {
        "chapter": "第6章", "section": "6.5", "question_type": "calc", "difficulty": "hard",
        "question_text": "求方程 x₁+x₂+x₃+x₄=15 的非负整数解的个数。",
        "options": "",
        "answer": "C(18,3)=816",
        "answer_cn": "关键步骤（星与条方法）：\n1. n=4 个变量之和为 k=15。\n2. 非负整数解数 = C(k+n−1, n−1) = C(15+4−1, 4−1) = C(18,3)。\n3. C(18,3) = 18×17×16/(3×2×1) = 4896/6 = 816。\n故解的个数为 816。",
        "tags": "星与条,组合,计数",
    },
    {
        "chapter": "第6章", "section": "6.6", "question_type": "calc", "difficulty": "hard",
        "question_text": "在 1 到 100 的整数中，能被 3 或 5 整除的整数有多少个？",
        "options": "",
        "answer": "47",
        "answer_cn": "关键步骤（容斥原理）：\n1. 设 A=被 3 整除的数，B=被 5 整除的数。\n2. |A| = ⌊100/3⌋ = 33。\n3. |B| = ⌊100/5⌋ = 20。\n4. |A∩B|（被 15 整除）= ⌊100/15⌋ = 6。\n5. 由容斥：|A∪B| = |A|+|B|−|A∩B| = 33+20−6 = 47。\n故 1 到 100 中能被 3 或 5 整除的整数有 47 个。",
        "tags": "容斥原理,计数",
    },
    {
        "chapter": "第6章", "section": "6.4", "question_type": "proof", "difficulty": "medium",
        "question_text": "证明：C(n,k) = C(n, n−k)（组合数的对称性）。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "证明关键步骤：\n1. 由定义 C(n,k) = n!/(k!·(n−k)!)。\n2. C(n, n−k) = n!/((n−k)!·(n−(n−k))!) = n!/((n−k)!·k!)。\n3. 比较两式，分子均为 n!，分母均为 k!·(n−k)!，故二者相等。\n4. 即 C(n,k) = C(n, n−k)。证毕。\n组合意义：从 n 个中选 k 个等价于选 n−k 个不选。",
        "tags": "组合数,对称性,证明",
    },
    {
        "chapter": "第6章", "section": "6.3", "question_type": "true_false", "difficulty": "easy",
        "question_text": "判断对错：鸽巢原理要求鸽子数大于鸽巢数时，至少有一个鸽巢含至少 2 只鸽子。",
        "options": "",
        "answer": "对",
        "answer_cn": "对。鸽巢原理：若将 m 个物体放入 n 个盒子且 m>n，则至少有一个盒子含至少 ⌈m/n⌉ 个物体；当 m=n+1 时至少有一个盒子含至少 2 个。",
        "tags": "鸽巢原理",
    },
    {
        "chapter": "第6章", "section": "6.5", "question_type": "short_answer", "difficulty": "medium",
        "question_text": "简述“星与条”（Stars and Bars）方法解决的问题类型及公式。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "星与条方法解决：将 k 个不可区分物体放入 n 个可区分盒子（允许空盒）的方案数。\n公式：C(k+n−1, n−1) = C(k+n−1, k)。\n直观：k 颗星（物体）+ n−1 条分隔（隔板），共 k+n−1 个位置选 n−1 个放条。\n等价问题：方程 x₁+x₂+…+xₙ=k 的非负整数解数。",
        "tags": "星与条,计数,组合",
    },

    # ===================== 第7章 离散概率 (10题) =====================
    {
        "chapter": "第7章", "section": "7.1", "question_type": "choice", "difficulty": "easy",
        "question_text": "掷一枚均匀硬币，正面朝上的概率是？",
        "options": "A. 1/4\nB. 1/3\nC. 1/2\nD. 2/3",
        "answer": "C",
        "answer_cn": "C. 1/2。硬币两面均匀，正面朝上的概率 = 有利事件数/总事件数 = 1/2。",
        "tags": "概率,均匀分布",
    },
    {
        "chapter": "第7章", "section": "7.1", "question_type": "choice", "difficulty": "medium",
        "question_text": "掷一颗均匀骰子，点数为偶数的概率是？",
        "options": "A. 1/6\nB. 1/3\nC. 1/2\nD. 2/3",
        "answer": "C",
        "answer_cn": "C. 1/2。骰子 6 个面，偶数有 2、4、6 共 3 个，概率 = 3/6 = 1/2。",
        "tags": "概率,古典概型",
    },
    {
        "chapter": "第7章", "section": "7.2", "question_type": "choice", "difficulty": "medium",
        "question_text": "若事件 A、B 独立，则 P(A∩B) = ?",
        "options": "A. P(A)+P(B)\nB. P(A)·P(B)\nC. P(A)−P(B)\nD. P(A∪B)",
        "answer": "B",
        "answer_cn": "B. P(A)·P(B)。两事件独立的充要条件是 P(A∩B) = P(A)·P(B)。",
        "tags": "独立事件,概率",
    },
    {
        "chapter": "第7章", "section": "7.2", "question_type": "choice", "difficulty": "medium",
        "question_text": "P(A∪B) 等于？",
        "options": "A. P(A)+P(B)\nB. P(A)·P(B)\nC. P(A)+P(B)−P(A∩B)\nD. P(A)+P(B)+P(A∩B)",
        "answer": "C",
        "answer_cn": "C. P(A)+P(B)−P(A∩B)。容斥原理在概率中的形式：P(A∪B) = P(A)+P(B)−P(A∩B)，避免重复计数 A∩B 部分。",
        "tags": "概率,容斥原理",
    },
    {
        "chapter": "第7章", "section": "7.3", "question_type": "choice", "difficulty": "hard",
        "question_text": "贝叶斯定理 P(A|B) 的完整表达式是？",
        "options": "A. P(B)/P(A)\nB. P(A∩B)/P(B)\nC. P(A∩B)/P(A)\nD. P(B|A)·P(A)/P(B)",
        "answer": "D",
        "answer_cn": "D. P(B|A)·P(A)/P(B)。贝叶斯定理：P(A|B) = P(B|A)·P(A)/P(B) = P(A∩B)/P(B)。选项 D 是完整形式。",
        "tags": "贝叶斯定理,条件概率",
    },
    {
        "chapter": "第7章", "section": "7.2", "question_type": "fill", "difficulty": "medium",
        "question_text": "条件概率 P(A|B) 的公式为____。",
        "options": "",
        "answer": "P(A∩B)/P(B)",
        "answer_cn": "P(A∩B)/P(B)。在事件 B 已发生条件下 A 发生的条件概率 P(A|B) = P(A∩B)/P(B)（要求 P(B)>0）。",
        "tags": "条件概率,公式",
    },
    {
        "chapter": "第7章", "section": "7.1", "question_type": "fill", "difficulty": "easy",
        "question_text": "必然事件的概率为____，不可能事件的概率为____。",
        "options": "",
        "answer": "1；0",
        "answer_cn": "1；0。必然事件（样本空间本身）概率为 1；不可能事件（空集）概率为 0。",
        "tags": "概率,基本性质",
    },
    {
        "chapter": "第7章", "section": "7.2", "question_type": "calc", "difficulty": "hard",
        "question_text": "袋中有 3 红 2 白球，无放回地连取 2 球，求两球都是红球的概率。",
        "options": "",
        "answer": "3/10",
        "answer_cn": "关键步骤：\n1. 总取法：C(5,2) = 10。\n2. 两红取法：C(3,2) = 3。\n3. 概率 = 3/10。\n或用条件概率：P = (3/5)×(2/4) = 6/20 = 3/10。",
        "tags": "概率,组合,无放回抽样",
    },
    {
        "chapter": "第7章", "section": "7.2", "question_type": "true_false", "difficulty": "easy",
        "question_text": "判断对错：若事件 A、B 互斥（不相容），则 P(A∪B) = P(A)+P(B)。",
        "options": "",
        "answer": "对",
        "answer_cn": "对。互斥事件 A∩B=∅，P(A∩B)=0，故 P(A∪B) = P(A)+P(B)−0 = P(A)+P(B)。",
        "tags": "互斥事件,概率",
    },
    {
        "chapter": "第7章", "section": "7.3", "question_type": "short_answer", "difficulty": "medium",
        "question_text": "简述贝叶斯定理的含义及其在实际中的应用场景。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "贝叶斯定理：P(A|B) = P(B|A)·P(A)/P(B)。\n含义：在观察到证据 B 后，由先验概率 P(A) 和似然 P(B|A) 推得后验概率 P(A|B)，更新对事件 A 的认知。\n应用场景：\n1. 医学诊断：根据检测结果推断患病概率。\n2. 垃圾邮件过滤：根据关键词推断邮件是否为垃圾邮件。\n3. 机器学习分类器（朴素贝叶斯）。",
        "tags": "贝叶斯定理,条件概率,应用",
    },

    # ===================== 第8章 高级计数 (8题) =====================
    {
        "chapter": "第8章", "section": "8.1", "question_type": "choice", "difficulty": "medium",
        "question_text": "递推关系 aₙ = 2aₙ₋₁, a₀=1 的通解为？",
        "options": "A. aₙ = n\nB. aₙ = 2ⁿ\nC. aₙ = 2n\nD. aₙ = n²",
        "answer": "B",
        "answer_cn": "B. aₙ = 2ⁿ。齐次递推 aₙ=2aₙ₋₁ 的特征根 r=2，aₙ = C·2ⁿ；由 a₀=1 得 C=1，故 aₙ=2ⁿ。",
        "tags": "递推关系,通解",
    },
    {
        "chapter": "第8章", "section": "8.2", "question_type": "choice", "difficulty": "medium",
        "question_text": "递推关系 aₙ = aₙ₋₁ + aₙ₋₂, a₀=0, a₁=1 是？",
        "options": "A. 阶乘数列\nB. 斐波那契数列\nC. 等差数列\nD. 等比数列",
        "answer": "B",
        "answer_cn": "B. 斐波那契数列。a₀=0, a₁=1, aₙ=aₙ₋₁+aₙ₋₂ 即斐波那契数列定义。",
        "tags": "斐波那契数列,递推关系",
    },
    {
        "chapter": "第8章", "section": "8.4", "question_type": "choice", "difficulty": "hard",
        "question_text": "生成函数 G(x) = 1/(1−2x) 对应的数列是？",
        "options": "A. aₙ = 1\nB. aₙ = 2ⁿ\nC. aₙ = n\nD. aₙ = n!",
        "answer": "B",
        "answer_cn": "B. aₙ = 2ⁿ。1/(1−2x) = Σ 2ⁿxⁿ，故对应数列 aₙ = 2ⁿ。",
        "tags": "生成函数,数列",
    },
    {
        "chapter": "第8章", "section": "8.1", "question_type": "choice", "difficulty": "medium",
        "question_text": "汉诺塔问题中移动 n 个盘所需最少步数 T(n) 满足？",
        "options": "A. T(n) = 2T(n−1)+1, T(1)=1\nB. T(n) = T(n−1)+1, T(1)=1\nC. T(n) = 2T(n−1), T(1)=1\nD. T(n) = n²",
        "answer": "A",
        "answer_cn": "A. T(n) = 2T(n−1)+1, T(1)=1。汉诺塔将 n−1 盘从源柱移到辅助柱（T(n−1)），再把最大盘移到目标柱（1 步），最后把 n−1 盘从辅助柱移到目标柱（T(n−1)），共 2T(n−1)+1 步。",
        "tags": "汉诺塔,递推关系",
    },
    {
        "chapter": "第8章", "section": "8.1", "question_type": "fill", "difficulty": "medium",
        "question_text": "汉诺塔问题移动 n 个盘所需最少步数为____。",
        "options": "",
        "answer": "2ⁿ−1",
        "answer_cn": "2ⁿ−1。由递推 T(n)=2T(n−1)+1, T(1)=1 解得 T(n)=2ⁿ−1。",
        "tags": "汉诺塔,递推",
    },
    {
        "chapter": "第8章", "section": "8.4", "question_type": "fill", "difficulty": "hard",
        "question_text": "数列 1,1,1,…（全 1 数列）的生成函数为____。",
        "options": "",
        "answer": "1/(1−x)",
        "answer_cn": "1/(1−x)。1/(1−x) = 1+x+x²+… = Σ xⁿ，各项系数均为 1，对应数列 aₙ=1。",
        "tags": "生成函数,数列",
    },
    {
        "chapter": "第8章", "section": "8.2", "question_type": "calc", "difficulty": "hard",
        "question_text": "解递推关系 aₙ = 5aₙ₋₁ − 6aₙ₋₂, a₀=1, a₁=5。",
        "options": "",
        "answer": "aₙ = −2·2ⁿ + 3·3ⁿ",
        "answer_cn": "关键步骤：\n1. 特征方程 r²−5r+6=0，解 r₁=2, r₂=3。\n2. 通解 aₙ = α·2ⁿ + β·3ⁿ。\n3. 代入初始条件：\n   a₀: α+β = 1\n   a₁: 2α+3β = 5\n4. 解方程组：由 α=1−β，代入 2(1−β)+3β=5，得 2+β=5，β=3，α=−2。\n5. 故 aₙ = −2·2ⁿ + 3·3ⁿ。\n核验：a₀=−2+3=1✓；a₁=−4+9=5✓。",
        "tags": "递推关系,特征方程,通解",
    },
    {
        "chapter": "第8章", "section": "8.4", "question_type": "short_answer", "difficulty": "medium",
        "question_text": "简述生成函数的概念及其在求解递推关系中的作用。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "生成函数：将数列 {aₙ} 转化为幂级数 G(x) = Σ aₙxⁿ。\n作用：\n1. 把递推关系转化为函数方程，便于代数操作。\n2. 通过展开 G(x) 求得 aₙ 的显式表达。\n3. 用于计算组合数、求解递推、分析算法复杂度。\n例：aₙ=2aₙ₋₁, a₀=1 对应 G(x)=1/(1−2x)，展开得 aₙ=2ⁿ。",
        "tags": "生成函数,递推关系",
    },

    # ===================== 第9章 关系 (15题) =====================
    {
        "chapter": "第9章", "section": "9.1", "question_type": "choice", "difficulty": "easy",
        "question_text": "集合 A={1,2} 上的二元关系总数为？",
        "options": "A. 2\nB. 4\nC. 8\nD. 16",
        "answer": "D",
        "answer_cn": "D. 16。A 上二元关系是 A×A 的子集，|A×A|=2²=4，子集数 2⁴=16。",
        "tags": "关系,二元关系",
    },
    {
        "chapter": "第9章", "section": "9.1", "question_type": "choice", "difficulty": "medium",
        "question_text": "若 |A|=n，则 A 上二元关系的个数为？",
        "options": "A. n²\nB. 2ⁿ\nC. 2^(n²)\nD. n!",
        "answer": "C",
        "answer_cn": "C. 2^(n²)。A×A 有 n² 个元素，其子集数即关系数为 2^(n²)。",
        "tags": "关系,计数",
    },
    {
        "chapter": "第9章", "section": "9.5", "question_type": "choice", "difficulty": "medium",
        "question_text": "下列关系性质中，等价关系必须满足的是？",
        "options": "A. 自反、对称、传递\nB. 自反、反对称、传递\nC. 对称、传递\nD. 自反、对称",
        "answer": "A",
        "answer_cn": "A. 自反、对称、传递。等价关系需同时满足自反性、对称性和传递性。",
        "tags": "等价关系,性质",
    },
    {
        "chapter": "第9章", "section": "9.5", "question_type": "choice", "difficulty": "medium",
        "question_text": "下列关系性质中，偏序关系必须满足的是？",
        "options": "A. 自反、对称、传递\nB. 自反、反对称、传递\nC. 反对称、传递\nD. 对称、传递",
        "answer": "B",
        "answer_cn": "B. 自反、反对称、传递。偏序关系需同时满足自反性、反对称性和传递性。",
        "tags": "偏序关系,性质",
    },
    {
        "chapter": "第9章", "section": "9.6", "question_type": "choice", "difficulty": "hard",
        "question_text": "等价关系 R 将集合 A 划分成的子集称为？",
        "options": "A. 极大元\nB. 等价类\nC. 偏序集\nD. 链",
        "answer": "B",
        "answer_cn": "B. 等价类。等价关系将集合划分为若干不相交的等价类，每个等价类 [a] = {x∈A | xRa}，所有等价类构成 A 的划分。",
        "tags": "等价关系,等价类,划分",
    },
    {
        "chapter": "第9章", "section": "9.1", "question_type": "choice", "difficulty": "easy",
        "question_text": "关系 R 的逆关系 R⁻¹ 定义为？",
        "options": "A. {(a,b) | (a,b)∈R}\nB. {(b,a) | (a,b)∈R}\nC. {(a,b) | (a,b)∉R}\nD. R∪R",
        "answer": "B",
        "answer_cn": "B. {(b,a) | (a,b)∈R}。逆关系 R⁻¹ 是将 R 中每个序偶 (a,b) 改为 (b,a) 得到的关系。",
        "tags": "逆关系,关系",
    },
    {
        "chapter": "第9章", "section": "9.1", "question_type": "fill", "difficulty": "medium",
        "question_text": "若关系 R 满足：对任意 a∈A 都有 (a,a)∈R，则称 R 具有____性。",
        "options": "",
        "answer": "自反",
        "answer_cn": "自反。自反性要求每个元素都与自身相关。",
        "tags": "自反性,关系性质",
    },
    {
        "chapter": "第9章", "section": "9.1", "question_type": "fill", "difficulty": "medium",
        "question_text": "若 (a,b)∈R 蕴含 (b,a)∈R，则称 R 具有____性。",
        "options": "",
        "answer": "对称",
        "answer_cn": "对称。对称性要求 a 与 b 相关则 b 与 a 也相关。",
        "tags": "对称性,关系性质",
    },
    {
        "chapter": "第9章", "section": "9.1", "question_type": "fill", "difficulty": "medium",
        "question_text": "若 (a,b)∈R 且 (b,c)∈R 蕴含 (a,c)∈R，则称 R 具有____性。",
        "options": "",
        "answer": "传递",
        "answer_cn": "传递。传递性要求 aRb 且 bRc 推出 aRc。",
        "tags": "传递性,关系性质",
    },
    {
        "chapter": "第9章", "section": "9.5", "question_type": "calc", "difficulty": "medium",
        "question_text": "集合 A={1,2,3,4} 上的关系 R={(1,1),(2,2),(3,3),(4,4),(1,2),(2,1)}，判断 R 是否为等价关系，若是求其等价类。",
        "options": "",
        "answer": "是等价关系，等价类为 {1,2}、{3}、{4}",
        "answer_cn": "关键步骤：\n1. 自反性：含 (1,1),(2,2),(3,3),(4,4)，满足。\n2. 对称性：(1,2) 与 (2,1) 互逆，对角元自逆，满足。\n3. 传递性：(1,2),(2,1) 推 (1,1)∈R ✓；(2,1),(1,2) 推 (2,2)∈R ✓；其余自反，满足。\n4. 故 R 是等价关系。\n5. 等价类：[1]=[2]={1,2}；[3]={3}；[4]={4}。\n故划分为 {{1,2}, {3}, {4}}。",
        "tags": "等价关系,等价类,计算",
    },
    {
        "chapter": "第9章", "section": "9.6", "question_type": "calc", "difficulty": "hard",
        "question_text": "求关系 R={(1,1),(1,2),(2,3),(3,1)} 在集合 {1,2,3} 上的传递闭包（用 Warshall 算法）。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "关键步骤（Warshall 算法）：\n1. 初始邻接矩阵 M（行列为 1,2,3）：\n   M = [[1,1,0],[0,0,1],[1,0,0]]\n2. k=1：经过 1。M[3][1]=1，将行 3 与行 1 求或：行3=[1,0,0]∨[1,1,0]=[1,1,0]。\n   M = [[1,1,0],[0,0,1],[1,1,0]]\n3. k=2：经过 2。M[1][2]=1，行1∨行2=[1,1,0]∨[0,0,1]=[1,1,1]；M[3][2]=1，行3∨行2=[1,1,0]∨[0,0,1]=[1,1,1]。\n   M = [[1,1,1],[0,0,1],[1,1,1]]\n4. k=3：经过 3。M[1][3]=1，行1∨行3=[1,1,1]∨[1,1,1]=[1,1,1]；M[3][3]=1，行3∨行3不变。\n   M = [[1,1,1],[0,0,1],[1,1,1]]\n5. 传递闭包 R⁺ = {(1,1),(1,2),(1,3),(2,3),(3,1),(3,2),(3,3)}。",
        "tags": "传递闭包,Warshall算法",
    },
    {
        "chapter": "第9章", "section": "9.5", "question_type": "proof", "difficulty": "medium",
        "question_text": "证明：若 R 是集合 A 上的等价关系，则 R 的等价类构成 A 的一个划分。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "证明关键步骤：\n1. 非空：由自反性 a∈[a]，每个等价类非空。\n2. 覆盖：对任意 a∈A，a∈[a]，故 A⊆∪[a]，又 [a]⊆A 故 ∪[a]=A。\n3. 不相交：设 [a]∩[b]≠∅，取 c∈[a]∩[b]，则 cRa, cRb，由对称性 aRc, cRb，传递性得 aRb，故 b∈[a]，进而 [b]=[a]。\n4. 故等价类两两不相交且覆盖 A，构成 A 的划分。证毕。",
        "tags": "等价关系,划分,证明",
    },
    {
        "chapter": "第9章", "section": "9.6", "question_type": "proof", "difficulty": "hard",
        "question_text": "证明：集合 A 上关系 R 的传递闭包 R⁺ 等于 R 的所有幂的并 ∪_{i=1}^∞ Rⁱ。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "证明关键步骤：\n1. 设 T = ∪_{i=1}^∞ Rⁱ。\n2. T 传递：若 (a,b)∈T 且 (b,c)∈T，则存在 i,j 使 (a,b)∈Rⁱ, (b,c)∈Rʲ，故 (a,c)∈R^(i+j)⊆T。\n3. T 包含 R：R=R¹⊆T。\n4. T 最小：设 S 传递且包含 R，则 Rⁱ⊆S（归纳），故 T⊆S。\n5. 故 T 是包含 R 的最小传递关系，即传递闭包 R⁺=T。证毕。",
        "tags": "传递闭包,证明",
    },
    {
        "chapter": "第9章", "section": "9.6", "question_type": "true_false", "difficulty": "medium",
        "question_text": "判断对错：等价关系与集合的划分一一对应。",
        "options": "",
        "answer": "对",
        "answer_cn": "对。每个等价关系唯一确定一个划分（其等价类集合）；反之每个划分唯一确定一个等价关系（同属一块的元素相关），二者一一对应。",
        "tags": "等价关系,划分",
    },
    {
        "chapter": "第9章", "section": "9.5", "question_type": "short_answer", "difficulty": "medium",
        "question_text": "简述等价关系与偏序关系的定义及其区别。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "等价关系：自反、对称、传递。用于分类，将集合划分为等价类。例：整数模 n 同余。\n偏序关系：自反、反对称、传递。用于排序，反映元素间“小于等于”类关系。例：整除关系、子集包含。\n区别：等价关系对称，偏序关系反对称；等价关系描述“相同类”，偏序关系描述“先后顺序”。",
        "tags": "等价关系,偏序关系,对比",
    },

    # ===================== 第10章 图论 (20题) =====================
    {
        "chapter": "第10章", "section": "10.1", "question_type": "choice", "difficulty": "easy",
        "question_text": "无向图中顶点度数之和与边数的关系是？",
        "options": "A. 度数之和 = 边数\nB. 度数之和 = 2×边数\nC. 度数之和 = 边数/2\nD. 度数之和 = 边数²",
        "answer": "B",
        "answer_cn": "B. 度数之和 = 2×边数。握手定理：每条边贡献两端各 1 度，故顶点度数之和等于边数的两倍。",
        "tags": "图论,握手定理,度数",
    },
    {
        "chapter": "第10章", "section": "10.2", "question_type": "choice", "difficulty": "medium",
        "question_text": "完全图 Kₙ 的边数为？",
        "options": "A. n\nB. n(n−1)\nC. n(n−1)/2\nD. n²",
        "answer": "C",
        "answer_cn": "C. n(n−1)/2。完全图 Kₙ 中任意两顶点之间恰有一条边，边数为 C(n,2) = n(n−1)/2。",
        "tags": "完全图,边数",
    },
    {
        "chapter": "第10章", "section": "10.4", "question_type": "choice", "difficulty": "medium",
        "question_text": "二分图 K_{m,n} 的边数为？",
        "options": "A. m+n\nB. mn\nC. m·n/2\nD. C(m+n,2)",
        "answer": "B",
        "answer_cn": "B. mn。完全二分图 K_{m,n} 中第一部分每个顶点与第二部分每个顶点相连，共 m×n 条边。",
        "tags": "二分图,边数",
    },
    {
        "chapter": "第10章", "section": "10.5", "question_type": "choice", "difficulty": "medium",
        "question_text": "连通无向图 G 是欧拉图的充要条件是？",
        "options": "A. 所有顶点度数为偶数\nB. 所有顶点度数为奇数\nC. 恰有两个奇点\nD. 顶点数偶数",
        "answer": "A",
        "answer_cn": "A. 所有顶点度数为偶数。连通图存在欧拉回路（每边恰走一次）的充要条件是所有顶点度数均为偶数。",
        "tags": "欧拉图,欧拉回路",
    },
    {
        "chapter": "第10章", "section": "10.5", "question_type": "choice", "difficulty": "medium",
        "question_text": "连通无向图存在欧拉通路（非回路）的充要条件是？",
        "options": "A. 所有顶点度数为偶数\nB. 恰有 0 个奇点\nC. 恰有 2 个奇点\nD. 恰有 4 个奇点",
        "answer": "C",
        "answer_cn": "C. 恰有 2 个奇点。连通图存在欧拉通路（不回到起点）的充要条件是恰有两个奇数度顶点，作为通路的起点和终点。",
        "tags": "欧拉通路,奇点",
    },
    {
        "chapter": "第10章", "section": "10.6", "question_type": "choice", "difficulty": "medium",
        "question_text": "n 个顶点的树恰好有多少条边？",
        "options": "A. n\nB. n−1\nC. n+1\nD. 2n",
        "answer": "B",
        "answer_cn": "B. n−1。树是连通无圈图，n 个顶点的树恰有 n−1 条边。",
        "tags": "树,边数",
    },
    {
        "chapter": "第10章", "section": "10.7", "question_type": "choice", "difficulty": "hard",
        "question_text": "彼得森图（Petersen graph）的色数为？",
        "options": "A. 2\nB. 3\nC. 4\nD. 5",
        "answer": "B",
        "answer_cn": "B. 3。彼得森图是 3-正则图，含奇圈故非二分图，色数 ≥3；可构造 3-着色，故色数为 3。",
        "tags": "彼得森图,色数,图着色",
    },
    {
        "chapter": "第10章", "section": "10.7", "question_type": "choice", "difficulty": "hard",
        "question_text": "连通平面图的欧拉公式 V−E+F 等于？",
        "options": "A. 0\nB. 1\nC. 2\nD. −1",
        "answer": "C",
        "answer_cn": "C. 2。连通平面图的欧拉公式：V−E+F = 2，其中 V 为顶点数、E 为边数、F 为面数（含外面）。",
        "tags": "平面图,欧拉公式",
    },
    {
        "chapter": "第10章", "section": "10.1", "question_type": "fill", "difficulty": "easy",
        "question_text": "图中顶点 v 的度数记作 deg(v)，表示与 v 关联的____数。",
        "options": "",
        "answer": "边",
        "answer_cn": "边。度数 deg(v) 是与顶点 v 关联的边数（自环计两次）。",
        "tags": "度数,图论",
    },
    {
        "chapter": "第10章", "section": "10.2", "question_type": "fill", "difficulty": "medium",
        "question_text": "若图 G 中任意两顶点间都存在路径，则称 G 为____图。",
        "options": "",
        "answer": "连通",
        "answer_cn": "连通。无向图任意两顶点可达则称连通图；有向图任意两顶点互相可达则称强连通图。",
        "tags": "连通图,图论",
    },
    {
        "chapter": "第10章", "section": "10.7", "question_type": "fill", "difficulty": "hard",
        "question_text": "Kuratowski 定理指出：一个图是平面图当且仅当它不包含与 K₅ 或 K_{3,3} 同胚的子图。其中 K₅ 是____图。",
        "options": "",
        "answer": "5个顶点的完全",
        "answer_cn": "5个顶点的完全。K₅ 是 5 个顶点的完全图，K_{3,3} 是 3+3 个顶点的完全二分图。Kuratowski 定理指出二者是平面图的禁用同胚子图。",
        "tags": "平面图,Kuratowski定理",
    },
    {
        "chapter": "第10章", "section": "10.6", "question_type": "fill", "difficulty": "medium",
        "question_text": "不包含任何回路的连通图称为____。",
        "options": "",
        "answer": "树",
        "answer_cn": "树。树是连通无圈（无回路）的无向图，n 个顶点的树恰有 n−1 条边。",
        "tags": "树,无回路",
    },
    {
        "chapter": "第10章", "section": "10.1", "question_type": "calc", "difficulty": "medium",
        "question_text": "一个图有 6 个顶点，度数序列为 3,3,3,3,3,3，求其边数。",
        "options": "",
        "answer": "9",
        "answer_cn": "关键步骤：\n1. 由握手定理，度数之和 = 2×边数。\n2. 度数之和 = 3×6 = 18。\n3. 边数 = 18/2 = 9。\n故该图有 9 条边（即 3-正则图 K_{3,3} 或三角棱柱图等）。",
        "tags": "握手定理,度数,边数",
    },
    {
        "chapter": "第10章", "section": "10.2", "question_type": "calc", "difficulty": "medium",
        "question_text": "求完全图 K₆ 的边数。",
        "options": "",
        "answer": "15",
        "answer_cn": "关键步骤：\n1. Kₙ 边数为 C(n,2) = n(n−1)/2。\n2. K₆ 边数 = 6×5/2 = 15。",
        "tags": "完全图,边数",
    },
    {
        "chapter": "第10章", "section": "10.7", "question_type": "calc", "difficulty": "hard",
        "question_text": "已知一个连通平面图有 V=8 个顶点，E=12 条边，求面数 F。",
        "options": "",
        "answer": "F=6",
        "answer_cn": "关键步骤：\n1. 由欧拉公式 V−E+F = 2。\n2. 代入 8−12+F = 2，得 F = 6。\n故该平面图有 6 个面（含外部面）。",
        "tags": "欧拉公式,平面图,计算",
    },
    {
        "chapter": "第10章", "section": "10.1", "question_type": "proof", "difficulty": "medium",
        "question_text": "证明握手定理：无向图中所有顶点度数之和等于边数的两倍。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "证明关键步骤：\n1. 设图 G 有 n 个顶点 v₁,…,vₙ 和 m 条边 e₁,…,eₘ。\n2. 每条边 e=(u,v) 在计算度数时，对 u 和 v 各贡献 1（共 2）。\n3. 故 Σ deg(vᵢ) = 2m。\n4. 即度数之和等于边数的两倍。证毕。\n推论：度数为奇数的顶点个数为偶数。",
        "tags": "握手定理,证明",
    },
    {
        "chapter": "第10章", "section": "10.6", "question_type": "proof", "difficulty": "medium",
        "question_text": "证明：n 个顶点的树恰有 n−1 条边。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "证明关键步骤（对 n 归纳）：\n1. 基础：n=1 时树无边（0=1−1），成立。\n2. 归纳假设：设 k 个顶点的树有 k−1 条边。\n3. 归纳步：设 T 有 k+1 个顶点。树是无圈连通图，必含度数为 1 的叶节点 v（否则所有度数≥2 形成回路）。\n4. 删去 v 及其关联边 e 得 T′，T′ 仍是树（连通无圈），顶点数 k，由假设边数 k−1。\n5. T 的边数 = T′ 边数 + 1 = (k−1)+1 = k = (k+1)−1。\n6. 由归纳法，n 个顶点的树恰有 n−1 条边。证毕。",
        "tags": "树,边数,数学归纳法",
    },
    {
        "chapter": "第10章", "section": "10.5", "question_type": "proof", "difficulty": "hard",
        "question_text": "证明：连通无向图 G 存在欧拉回路当且仅当 G 中所有顶点度数均为偶数。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "证明关键步骤：\n⇒（必要性）：设 G 有欧拉回路 C。回路每次进入并离开一个顶点，故每个顶点度数为偶数。\n⇐（充分性）：设 G 连通且所有顶点度数为偶数。从任一顶点 v 出发，沿未走边构造路径直到回到 v，得到回路 C。\n - 若 C 包含所有边，则 C 即欧拉回路。\n - 否则删去 C 中边得若干子图，每个连通分量顶点度数仍偶数且与 C 相交。从交点出发再构造回路并合并入 C。\n - 重复直至所有边被走完，得欧拉回路。\n故 G 存在欧拉回路当且仅当所有顶点度数均为偶数。证毕。",
        "tags": "欧拉回路,证明,充要条件",
    },
    {
        "chapter": "第10章", "section": "10.1", "question_type": "true_false", "difficulty": "easy",
        "question_text": "判断对错：在任何无向图中，度数为奇数的顶点个数必为偶数。",
        "options": "",
        "answer": "对",
        "answer_cn": "对。由握手定理 Σdeg(v)=2m 为偶数，故奇数度顶点个数必为偶数。",
        "tags": "握手定理,奇点",
    },
    {
        "chapter": "第10章", "section": "10.5", "question_type": "short_answer", "difficulty": "medium",
        "question_text": "简述欧拉回路与哈密顿回路的区别。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "区别：\n1. 欧拉回路：经过图中每条边恰一次的回路（边遍历）。判定：连通且所有顶点度数为偶数。\n2. 哈密顿回路：经过图中每个顶点恰一次的回路（顶点遍历）。判定：无简单充要条件，常用充分条件如 Dirac 定理（每个顶点度数≥n/2）。\n区别要点：欧拉关注“边”，哈密顿关注“顶点”。",
        "tags": "欧拉回路,哈密顿回路,对比",
    },

    # ===================== 第11章 树 (15题) =====================
    {
        "chapter": "第11章", "section": "11.1", "question_type": "choice", "difficulty": "easy",
        "question_text": "下列关于树的描述错误的是？",
        "options": "A. 树是连通无圈图\nB. n 个顶点的树有 n−1 条边\nC. 树中任意两顶点间存在唯一路径\nD. 树中一定存在回路",
        "answer": "D",
        "answer_cn": "D. 树中一定存在回路。错误，树是无圈（无回路）的连通图。A、B、C 都是树的正确性质。",
        "tags": "树,性质",
    },
    {
        "chapter": "第11章", "section": "11.1", "question_type": "choice", "difficulty": "medium",
        "question_text": "一棵有 n（n≥2）个顶点的树，其叶子节点数（度数为1）至少为？",
        "options": "A. 1\nB. 2\nC. n/2\nD. n−1",
        "answer": "B",
        "answer_cn": "B. 2。任意至少含 2 个顶点的树至少有 2 个叶节点（度数为 1 的顶点）。",
        "tags": "树,叶节点",
    },
    {
        "chapter": "第11章", "section": "11.4", "question_type": "choice", "difficulty": "medium",
        "question_text": "n 个顶点的二叉树（不一定平衡）的高度（根高度为0）最大为？",
        "options": "A. log₂n\nB. n−1\nC. ⌈log₂n⌉\nD. n/2",
        "answer": "B",
        "answer_cn": "B. n−1。退化为链状时高度最大为 n−1（每个内部节点只有一个子节点）。完全（满）二叉树高度为 ⌊log₂n⌋。",
        "tags": "二叉树,高度",
    },
    {
        "chapter": "第11章", "section": "11.5", "question_type": "choice", "difficulty": "medium",
        "question_text": "在二叉树的前序遍历中，根节点的访问顺序是？",
        "options": "A. 先于左右子树\nB. 介于左右子树之间\nC. 后于左右子树\nD. 任意位置",
        "answer": "A",
        "answer_cn": "A. 先于左右子树。前序遍历顺序为：根→左子树→右子树，根最先访问。",
        "tags": "二叉树,前序遍历",
    },
    {
        "chapter": "第11章", "section": "11.2", "question_type": "choice", "difficulty": "hard",
        "question_text": "求最小生成树的 Kruskal 算法使用的策略是？",
        "options": "A. 深度优先\nB. 广度优先\nC. 贪心选择最短边且不构成圈\nD. 动态规划",
        "answer": "C",
        "answer_cn": "C. 贪心选择最短边且不构成圈。Kruskal 算法按边权升序选择不构成圈的边，逐步加入生成树，是贪心算法。",
        "tags": "最小生成树,Kruskal算法",
    },
    {
        "chapter": "第11章", "section": "11.1", "question_type": "fill", "difficulty": "easy",
        "question_text": "连通无圈的无向图称为____。",
        "options": "",
        "answer": "树",
        "answer_cn": "树。树是连通且不含回路（圈）的无向图。",
        "tags": "树,定义",
    },
    {
        "chapter": "第11章", "section": "11.1", "question_type": "fill", "difficulty": "medium",
        "question_text": "度数为 1 的树节点称为____节点。",
        "options": "",
        "answer": "叶（叶子）",
        "answer_cn": "叶（叶子）。度数为 1 的顶点称为叶节点，度数大于 1 的称为内部节点。",
        "tags": "树,叶节点",
    },
    {
        "chapter": "第11章", "section": "11.4", "question_type": "fill", "difficulty": "medium",
        "question_text": "二叉树的三种基本遍历方式是前序遍历、____遍历和后序遍历。",
        "options": "",
        "answer": "中序",
        "answer_cn": "中序。二叉树三种基本遍历：前序（根左右）、中序（左根右）、后序（左右根）。",
        "tags": "二叉树,遍历",
    },
    {
        "chapter": "第11章", "section": "11.4", "question_type": "calc", "difficulty": "medium",
        "question_text": "已知二叉树前序遍历为 A B D E C F，中序遍历为 D B E A C F，描述该二叉树的结构。",
        "options": "",
        "answer": "根 A，左子树以 B 为根（D 左子，E 右子），右子树以 C 为根（F 为右子）",
        "answer_cn": "关键步骤：\n1. 前序首元素 A 为根。\n2. 在中序中 A 把序列分为左子树 D B E 和右子树 C F。\n3. 左子树前序 B D E，中序 D B E：B 为根，D 在左、E 在右。\n4. 右子树前序 C F，中序 C F：C 为根，F 在右。\n5. 结构：根 A，A 左子 B，B 左子 D、右子 E；A 右子 C，C 右子 F。",
        "tags": "二叉树,前序中序遍历,重建",
    },
    {
        "chapter": "第11章", "section": "11.2", "question_type": "calc", "difficulty": "hard",
        "question_text": "用 Kruskal 算法求带权图最小生成树：顶点 {1,2,3,4}，边权为 (1,2):1, (2,3):2, (3,4):3, (1,4):6, (1,3):5。",
        "options": "",
        "answer": "MST 边为 (1,2),(2,3),(3,4)，权总和 1+2+3=6",
        "answer_cn": "关键步骤：\n1. 按权升序排序：(1,2):1, (2,3):2, (3,4):3, (1,3):5, (1,4):6。\n2. 选 (1,2):1，不构成圈，加入。\n3. 选 (2,3):2，不构成圈（顶点 1,2,3），加入。\n4. 选 (3,4):3，加入（顶点 1,2,3,4 已全连通）。\n5. 已选 3 条边连接 4 个顶点，完成。\n6. MST 总权 = 1+2+3 = 6。",
        "tags": "最小生成树,Kruskal算法",
    },
    {
        "chapter": "第11章", "section": "11.1", "question_type": "proof", "difficulty": "medium",
        "question_text": "证明：树中任意两顶点之间存在唯一路径。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "证明关键步骤：\n1. 存在性：树是连通图，由定义任意两顶点 u, v 间存在路径。\n2. 唯一性（反证）：设 u, v 间有两条不同路径 P₁, P₂。\n3. 沿 P₁ 从 u 到 v，再沿 P₂ 反向从 v 回 u，形成一个闭合行走。\n4. 在该闭合行走中必可提取一个圈（回路），与树无圈矛盾。\n5. 故假设不成立，u, v 间路径唯一。证毕。",
        "tags": "树,路径唯一性,证明",
    },
    {
        "chapter": "第11章", "section": "11.1", "question_type": "proof", "difficulty": "hard",
        "question_text": "证明：连通图 G 是树当且仅当 G 中删除任一边后不连通。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "证明关键步骤：\n⇒（必要性）：设 G 是树，删去边 e=(u,v)。若仍连通，则 u, v 间存在不经过 e 的路径 P，但 P 与 e 形成圈，与树无圈矛盾。故删去任一边后不连通。\n⇐（充分性）：设 G 连通且删去任一边后不连通。若 G 含圈 C，删去 C 中任一边 e，C 中其余边仍连接 e 的两端，故 G−e 仍连通，与条件矛盾。故 G 无圈，连通无圈即树。\n证毕。",
        "tags": "树,连通性,证明",
    },
    {
        "chapter": "第11章", "section": "11.4", "question_type": "proof", "difficulty": "medium",
        "question_text": "证明：n 个节点的满二叉树（每个内部节点恰有两个子节点）有 (n+1)/2 个叶节点（n 为奇数）。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "证明关键步骤：\n1. 设满二叉树有 n 个节点，其中 i 个内部节点，l 个叶节点，n=i+l。\n2. 每个内部节点有 2 个子节点，故边数 = 2i。\n3. 又边数 = n−1（树性质）。\n4. 故 2i = n−1，i = (n−1)/2。\n5. l = n−i = n−(n−1)/2 = (n+1)/2。\n6. 故叶节点数为 (n+1)/2。证毕。",
        "tags": "满二叉树,叶节点,证明",
    },
    {
        "chapter": "第11章", "section": "11.1", "question_type": "true_false", "difficulty": "easy",
        "question_text": "判断对错：树中任意两个顶点之间存在唯一的简单路径。",
        "options": "",
        "answer": "对",
        "answer_cn": "对。树是连通无圈图，任意两顶点间存在且仅存在一条简单路径；若存在两条则形成圈，矛盾。",
        "tags": "树,路径唯一性",
    },
    {
        "chapter": "第11章", "section": "11.5", "question_type": "short_answer", "difficulty": "medium",
        "question_text": "简述二叉树前序、中序、后序遍历的顺序，并说明已知前序和中序能否唯一确定二叉树。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "遍历顺序：\n1. 前序：根 → 左子树 → 右子树\n2. 中序：左子树 → 根 → 右子树\n3. 后序：左子树 → 右子树 → 根\n唯一性：已知前序和中序可唯一确定二叉树。前序首元素为根，在中序中定位根，左右分为左右子树的中序，递归处理即可。同理，中序+后序也可唯一确定；但前序+后序一般不能唯一确定。",
        "tags": "二叉树,遍历,前序中序",
    },

    # ===================== 第12章 布尔代数 (8题) =====================
    {
        "chapter": "第12章", "section": "12.1", "question_type": "choice", "difficulty": "easy",
        "question_text": "布尔代数中，x∧1 = ?",
        "options": "A. 0\nB. 1\nC. x\nD. x¯",
        "answer": "C",
        "answer_cn": "C. x。同一律：x∧1 = x，1 是 ∧ 运算的单位元。",
        "tags": "布尔代数,同一律",
    },
    {
        "chapter": "第12章", "section": "12.1", "question_type": "choice", "difficulty": "medium",
        "question_text": "布尔代数中，x∨x¯ = ?",
        "options": "A. 0\nB. 1\nC. x\nD. x¯",
        "answer": "B",
        "answer_cn": "B. 1。互补律：x∨x¯ = 1，任一元素与其补之或为 1。",
        "tags": "布尔代数,互补律",
    },
    {
        "chapter": "第12章", "section": "12.1", "question_type": "choice", "difficulty": "medium",
        "question_text": "布尔代数中，x∧x = ?",
        "options": "A. 0\nB. 1\nC. x\nD. x¯",
        "answer": "C",
        "answer_cn": "C. x。幂等律：x∧x = x，元素与自身的与等于自身。",
        "tags": "布尔代数,幂等律",
    },
    {
        "chapter": "第12章", "section": "12.2", "question_type": "choice", "difficulty": "hard",
        "question_text": "布尔表达式 x∧(y∨x) 化简结果为？",
        "options": "A. x∧y\nB. x\nC. y\nD. x∨y",
        "answer": "B",
        "answer_cn": "B. x。由吸收律：x∧(y∨x) = x∧(x∨y) = x（吸收律第一式）。",
        "tags": "布尔代数,吸收律,化简",
    },
    {
        "chapter": "第12章", "section": "12.1", "question_type": "fill", "difficulty": "easy",
        "question_text": "布尔代数中，x∨0 = ____。",
        "options": "",
        "answer": "x",
        "answer_cn": "x。同一律：x∨0 = x，0 是 ∨ 运算的单位元（零元是 ∧ 的）。",
        "tags": "布尔代数,同一律",
    },
    {
        "chapter": "第12章", "section": "12.2", "question_type": "calc", "difficulty": "medium",
        "question_text": "化简布尔表达式 (x∧y)∨(x∧y¯)。",
        "options": "",
        "answer": "x",
        "answer_cn": "关键步骤：\n1. (x∧y)∨(x∧y¯) = x∧(y∨y¯)（分配律）\n2. y∨y¯ = 1（互补律）\n3. x∧1 = x（同一律）\n故化简结果为 x。",
        "tags": "布尔代数,化简,分配律",
    },
    {
        "chapter": "第12章", "section": "12.2", "question_type": "proof", "difficulty": "hard",
        "question_text": "证明布尔代数的德摩根律：¬(x∧y) = x¯∨y¯。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "证明关键步骤：\n1. 设 z = ¬(x∧y)，需证 z = x¯∨y¯。\n2. (x∧y)∧(x¯∨y¯) = (x∧y∧x¯)∨(x∧y∧y¯) = 0∨0 = 0（互补律）。\n3. (x∧y)∨(x¯∨y¯) = (x∨x¯∨y¯)∧(y∨x¯∨y¯) = (1∨y¯)∧(1∨x¯) = 1∧1 = 1。\n4. 由 2、3 知 x¯∨y¯ 满足 (x∧y) 的补元的定义，由补元唯一性得 ¬(x∧y) = x¯∨y¯。证毕。",
        "tags": "布尔代数,德摩根律,证明",
    },
    {
        "chapter": "第12章", "section": "12.1", "question_type": "true_false", "difficulty": "easy",
        "question_text": "判断对错：在布尔代数中，x∧x¯ = 0。",
        "options": "",
        "answer": "对",
        "answer_cn": "对。互补律：x∧x¯ = 0，任一元素与其补之与为 0。",
        "tags": "布尔代数,互补律",
    },

    # ===================== 第13章 计算模型 (7题) =====================
    {
        "chapter": "第13章", "section": "13.1", "question_type": "choice", "difficulty": "medium",
        "question_text": "有限状态机（FSM）由哪几部分组成？",
        "options": "A. 状态集、输入集、输出集、转移函数\nB. 状态集、输入集、转移函数、初始状态\nC. 状态集、输出集、转移函数\nD. 输入集、输出集、转移函数",
        "answer": "B",
        "answer_cn": "B. 状态集、输入集、转移函数、初始状态。有限状态机形式化为五元组 (S, I, δ, s₀, F) 或不含终态的 (S, I, δ, s₀)，核心是状态集、输入字母表、转移函数和初始状态。",
        "tags": "有限状态机,计算模型",
    },
    {
        "chapter": "第13章", "section": "13.2", "question_type": "choice", "difficulty": "medium",
        "question_text": "图灵机中读写头的操作不包括？",
        "options": "A. 左移\nB. 右移\nC. 停止\nD. 复制",
        "answer": "D",
        "answer_cn": "D. 复制。图灵机读写头每步可向左移、向右移或保持不动，并改写当前格内容，但不能直接“复制”单元内容。",
        "tags": "图灵机,读写头",
    },
    {
        "chapter": "第13章", "section": "13.3", "question_type": "choice", "difficulty": "hard",
        "question_text": "下列语言中，能被有限状态自动机识别的是？",
        "options": "A. {aⁿbⁿ | n≥0}\nB. {aⁿbⁿcⁿ | n≥0}\nC. 以 ab 结尾的所有字符串\nD. 任意长度的回文",
        "answer": "C",
        "answer_cn": "C. 以 ab 结尾的所有字符串。该语言是正则语言，可由有限状态自动机识别。A、B 不是正则语言（需计数），D 回文也不是正则语言。",
        "tags": "有限状态机,正则语言",
    },
    {
        "chapter": "第13章", "section": "13.1", "question_type": "fill", "difficulty": "medium",
        "question_text": "有限状态机中，从一个状态到另一个状态的迁移由____函数决定。",
        "options": "",
        "answer": "转移（δ）",
        "answer_cn": "转移（δ）。转移函数 δ: S×I → S 决定在当前状态读入输入符号后迁移到的新状态。",
        "tags": "有限状态机,转移函数",
    },
    {
        "chapter": "第13章", "section": "13.2", "question_type": "calc", "difficulty": "hard",
        "question_text": "图灵机包含哪些组成部分？简述其工作原理。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "图灵机组成：\n1. 有限状态集 Q、初始状态 q₀、终止状态集 F。\n2. 输入字母表 Σ、带字母表 Γ（含空白符 B）。\n3. 转移函数 δ: Q×Γ → Q×Γ×{L,R}。\n4. 无限长带子分格，每格存一个符号。\n5. 读写头，指向当前格。\n工作原理：每步根据当前状态 q 和读入符号 a，由 δ(q,a)=(q′,b,D) 写入符号 b、转移到状态 q′、读写头按 D 方向（L/R）移动一步；进入终止状态时停机，带上的内容即为输出。",
        "tags": "图灵机,工作原理",
    },
    {
        "chapter": "第13章", "section": "13.3", "question_type": "proof", "difficulty": "hard",
        "question_text": "证明：语言 L = {aⁿbⁿ | n≥0} 不是正则语言（不能用泵引理简述思路即可）。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "证明关键步骤（泵引理反证）：\n1. 假设 L 是正则语言，由泵引理存在泵长度 p。\n2. 取字符串 s = aᵖbᵖ∈L，|s|=2p≥p。\n3. 由泵引理 s 可分解为 xyz，|xy|≤p，|y|≥1，且对任意 i≥0，xyⁱz∈L。\n4. 由于 |xy|≤p，y 只能由 a 组成，即 y=aᵏ (k≥1)。\n5. 取 i=2，xy²z = aᵖ⁺ᵏbᵖ，a 数量 ≠ b 数量，不属于 L，矛盾。\n6. 故假设不成立，L 不是正则语言。证毕。",
        "tags": "正则语言,泵引理,证明",
    },
    {
        "chapter": "第13章", "section": "13.1", "question_type": "true_false", "difficulty": "easy",
        "question_text": "判断对错：图灵机的计算能力等价于现代计算机的理论计算能力。",
        "options": "",
        "answer": "对",
        "answer_cn": "对。丘奇-图灵论题指出：任何可有效计算的函数都可由图灵机计算，图灵机是现代计算机计算能力的理论模型。",
        "tags": "图灵机,丘奇图灵论题",
    },

    # ===================== 跨章节综合题 (15题) =====================
    {
        "chapter": "综合", "section": "1-2", "question_type": "choice", "difficulty": "medium",
        "question_text": "命题“对任意整数 n，若 n² 是偶数则 n 是偶数”的证明方法最适合用？",
        "options": "A. 直接证明\nB. 反证法\nC. 逆否命题证明\nD. 数学归纳法",
        "answer": "C",
        "answer_cn": "C. 逆否命题证明。原命题“若 n² 是偶数则 n 是偶数”等价于逆否命题“若 n 是奇数则 n² 是奇数”，后者更易直接证明。",
        "tags": "逆否命题,证明方法,综合",
    },
    {
        "chapter": "综合", "section": "1-2", "question_type": "choice", "difficulty": "hard",
        "question_text": "设 A={1,2,3}，A 上的关系 R 是“整除关系”，则 R 是？",
        "options": "A. 等价关系\nB. 偏序关系\nC. 既非等价也非偏序\nD. 既是等价又是偏序",
        "answer": "B",
        "answer_cn": "B. 偏序关系。整除关系满足自反（a|a）、反对称（若 a|b 且 b|a 则 a=b）、传递（a|b 且 b|c 推 a|c），故是偏序关系但不满足对称性，不是等价关系。",
        "tags": "偏序关系,整除,综合",
    },
    {
        "chapter": "综合", "section": "1-6", "question_type": "fill", "difficulty": "medium",
        "question_text": "用组合数证明 C(2n, n) 的奇偶性：C(2n,n) 总是____（奇/偶）。",
        "options": "",
        "answer": "偶",
        "answer_cn": "偶。关键思路：C(2n,n) = C(2n−1,n−1)+C(2n−1,n) = 2·C(2n−1,n−1)（由对称性 C(2n−1,n−1)=C(2n−1,n)），故 C(2n,n) 是偶数。",
        "tags": "组合数,奇偶性,综合",
    },
    {
        "chapter": "综合", "section": "1-6", "question_type": "fill", "difficulty": "medium",
        "question_text": "一个有 7 个人的群体中，至少有____个人的生日在同一个月（按12个月计）。",
        "options": "",
        "answer": "1",
        "answer_cn": "1。7 人放入 12 个月，鸽巢原理仅保证至少 ⌈7/12⌉=1 人同月（此问需要 13 人才保证 2 人同月）。注：若问“至少几人同月”答案是 1；若保证 2 人同月需 13 人。",
        "tags": "鸽巢原理,综合",
    },
    {
        "chapter": "综合", "section": "1-6", "question_type": "fill", "difficulty": "hard",
        "question_text": "用德摩根律将 ¬∀x∃y(P(x)∧Q(y)) 转换为只含存在量词的形式：____。",
        "options": "",
        "answer": "∃x∀y(¬P(x)∨¬Q(y))",
        "answer_cn": "∃x∀y(¬P(x)∨¬Q(y))。关键步骤：\n1. ¬∀x∃y(P(x)∧Q(y)) ≡ ∃x¬∃y(P(x)∧Q(y))\n2. ≡ ∃x∀y¬(P(x)∧Q(y))\n3. ≡ ∃x∀y(¬P(x)∨¬Q(y))（德摩根律）。",
        "tags": "量词否定,德摩根律,综合",
    },
    {
        "chapter": "综合", "section": "1-6", "question_type": "fill", "difficulty": "medium",
        "question_text": "排列 ABCDE 中，A 必须在 B 前面的排列数为____。",
        "options": "",
        "answer": "60",
        "answer_cn": "60。关键思路：5 个不同元素全排列 5!=120 种；A 在 B 前与 B 在 A 前对称各占一半，故 A 在 B 前的排列数为 120/2 = 60。",
        "tags": "排列,对称性,综合",
    },
    {
        "chapter": "综合", "section": "3-10", "question_type": "calc", "difficulty": "medium",
        "question_text": "用数学归纳法证明：n 个顶点的连通图至少有 n−1 条边。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "证明关键步骤（对 n 归纳）：\n1. 基础：n=1 时 0≥0，成立。\n2. 归纳假设：设 k 个顶点的连通图至少有 k−1 条边。\n3. 归纳步：设 G 有 k+1 个顶点且连通。G 中存在一个度数≥1 的顶点 v（否则不连通）。删去 v 及关联边得 G′，G′ 可能不连通，但每个连通分量顶点数之和为 k，由假设每个分量边数≥顶点数−1。\n4. G 的边数 = G′ 的边数 + 删除边数 ≥ (k−分量数) + 1 ≥ (k−1) + 0 ... 综合 G 边数 ≥ k = (k+1)−1。\n5. 故 n 个顶点的连通图至少有 n−1 条边。证毕。",
        "tags": "数学归纳法,图论,综合",
    },
    {
        "chapter": "综合", "section": "4-10", "question_type": "calc", "difficulty": "hard",
        "question_text": "在一个有 n 个顶点的简单无向图中，最多有多少条边？最少多少条边保证图连通？",
        "options": "",
        "answer": "最多 n(n−1)/2 条；连通至少 n−1 条",
        "answer_cn": "关键步骤：\n1. 最多边数：简单无向图任意两顶点至多一条边，最多为 C(n,2) = n(n−1)/2（完全图）。\n2. 连通至少边数：n 个顶点的连通图至少有 n−1 条边（树），因为连通无圈图（树）恰 n−1 边，且这是连通的最小边数。",
        "tags": "图论,边数,综合",
    },
    {
        "chapter": "综合", "section": "4-8", "question_type": "calc", "difficulty": "hard",
        "question_text": "用容斥原理求 1 到 1000 中不能被 2、3、5 任一整除的整数个数。",
        "options": "",
        "answer": "266",
        "answer_cn": "关键步骤（容斥原理）：\n1. 设 A=被2整除，B=被3整除，C=被5整除。\n2. |A|=500, |B|=333, |C|=200。\n3. |A∩B|=被6整除=166, |A∩C|=被10整除=100, |B∩C|=被15整除=66。\n4. |A∩B∩C|=被30整除=33。\n5. |A∪B∪C| = 500+333+200−166−100−66+33 = 734。\n6. 不能被2、3、5任一整除的数 = 1000−734 = 266。",
        "tags": "容斥原理,数论,综合",
    },
    {
        "chapter": "综合", "section": "1-13", "question_type": "true_false", "difficulty": "easy",
        "question_text": "判断对错：若命题 p 蕴含 q 且 q 蕴含 r，则 p 蕴含 r（三段论）。",
        "options": "",
        "answer": "对",
        "answer_cn": "对。这是假言三段论：p→q 与 q→r 可推出 p→r，是命题逻辑中的有效推理规则。",
        "tags": "假言三段论,推理规则,综合",
    },
    {
        "chapter": "综合", "section": "4-13", "question_type": "true_false", "difficulty": "medium",
        "question_text": "判断对错：每个正则语言都可以被有限状态自动机识别。",
        "options": "",
        "answer": "对",
        "answer_cn": "对。正则语言的定义就是能被有限状态自动机（DFA/NFA）识别的语言，二者等价（Kleene 定理）。",
        "tags": "正则语言,有限状态机,综合",
    },
    {
        "chapter": "综合", "section": "6-10", "question_type": "true_false", "difficulty": "hard",
        "question_text": "判断对错：完全图 K₅ 是平面图。",
        "options": "",
        "answer": "错",
        "answer_cn": "错。由 Kuratowski 定理，K₅ 含 5 顶点完全图，是平面图的禁用子图之一，故 K₅ 不是平面图（其边数 10 大于平面图上界 3·5−6=9）。",
        "tags": "平面图,完全图,Kuratowski定理,综合",
    },
    {
        "chapter": "综合", "section": "1-13", "question_type": "short_answer", "difficulty": "medium",
        "question_text": "简述离散数学中“证明”的常见方法，至少列举五种。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "常见证明方法：\n1. 直接证明：从已知条件出发，按逻辑规则推出结论。\n2. 反证法：假设结论不成立，导出矛盾。\n3. 逆否命题证明：证明原命题的逆否命题（与之等价）。\n4. 数学归纳法：基础步+归纳步，证明对全体正整数成立。\n5. 分情况证明：将条件分为若干情形分别证明。\n6. 构造性证明：直接构造满足条件的对象。\n7. 归谬法：假设存在性不成立，导出矛盾。",
        "tags": "证明方法,综合",
    },
    {
        "chapter": "综合", "section": "6-10", "question_type": "short_answer", "difficulty": "medium",
        "question_text": "简述图的矩阵表示法及其应用。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "图的矩阵表示：\n1. 邻接矩阵 A：A[i][j]=1 表示顶点 i 与 j 相邻（无向图对称）。用于判断连通性、计算路径数（Aⁿ 的元素表示长度为 n 的路径数）。\n2. 关联矩阵：行表示顶点、列表示边，反映顶点与边的关联关系。\n3. 距离矩阵：D[i][j] 表示顶点 i 到 j 的最短路径长度。\n应用：图的存储与计算、Warshall 算法求传递闭包、PageRank 等算法分析。",
        "tags": "图论,矩阵表示,综合",
    },
    {
        "chapter": "综合", "section": "1-13", "question_type": "short_answer", "difficulty": "hard",
        "question_text": "简述离散数学各章节之间的联系，至少说明三组章节间的关联。",
        "options": "",
        "answer": "见答案解析",
        "answer_cn": "章节联系：\n1. 第1章逻辑与第9章关系：关系可用命题逻辑描述其性质（自反、对称、传递对应逻辑条件）；关系运算遵循集合与逻辑的等价律。\n2. 第6章计数与第7章概率：概率计算的基础是计数（古典概型），组合数 C(n,k) 直接用于计算事件数。\n3. 第10章图论与第11章树：树是特殊的连通无圈图，图的欧拉回路、哈密顿回路与树的遍历密切相关；最小生成树是图论与树的交叉应用。\n4. 第5章归纳与第8章递推：递推关系的求解常用生成函数，数学归纳法证明递推公式的正确性。\n5. 第4章数论与第13章计算：RSA 密码学基于大整数分解困难，与图灵机可计算性、计算复杂性相关。",
        "tags": "章节联系,综合,离散数学",
    },
]


def import_quiz_data():
    """清空并重建试题库。

    流程：
      1. 清空 Quiz 表中的所有现有数据；
      2. 将 QUIZ_DATA 中的全部题目依次写入数据库；
      3. 为每道题设置 question_number、tags 等字段。

    返回：成功导入的题目数量 (int)。
    """
    from app import db
    from app.models import Quiz

    Quiz.query.delete()

    now = datetime.utcnow()
    for idx, item in enumerate(QUIZ_DATA, start=1):
        quiz = Quiz(
            chapter=item.get('chapter', ''),
            section=item.get('section', ''),
            question_number=idx,
            question_text=item.get('question_text', ''),
            question_type=item.get('question_type', 'choice'),
            options=item.get('options', ''),
            answer=item.get('answer', ''),
            answer_cn=item.get('answer_cn', ''),
            difficulty=item.get('difficulty', 'medium'),
            tags=item.get('tags', ''),
            created_at=now,
        )
        db.session.add(quiz)

    db.session.commit()
    return len(QUIZ_DATA)


def get_quiz_stats():
    """返回内置试题库的统计信息（不依赖数据库）。"""
    from collections import Counter
    chapter_counter = Counter(item.get('chapter', '') for item in QUIZ_DATA)
    type_counter = Counter(item.get('question_type', '') for item in QUIZ_DATA)
    difficulty_counter = Counter(item.get('difficulty', '') for item in QUIZ_DATA)
    return {
        'total': len(QUIZ_DATA),
        'by_chapter': dict(chapter_counter),
        'by_type': dict(type_counter),
        'by_difficulty': dict(difficulty_counter),
    }


def get_all_tags():
    """返回内置试题库中所有不重复的标签列表。"""
    tags_set = set()
    for item in QUIZ_DATA:
        tags = item.get('tags', '')
        if tags:
            for t in tags.split(','):
                t = t.strip()
                if t:
                    tags_set.add(t)
    return sorted(tags_set)
